### ISSUE TITLE
How to test the pre-trained model on my own data?

### ISSUE THREAD

**Issue by kliao4243** [VisualComputingInstitute/TrackR-CNN#10]
Thanks for sharing. I want to test the pre-trained model on my own data. How could I change the file path of the testing data?

**Comment by kliao4243** [comment]
Hi. Could you please explain what does "You'll need to adjust the KITTI_segtrack_data_dir and load_init flags to point to the KITTI MOTS data directory and the path to the pretrained model, respectively" specifically mean?

**Comment by Vankeee** [comment]
Hi, do you know to do it? I want to test my own dataset, @kliao4243

**Comment by pvoigtlaender** [comment]
Please first try to get it running on KITTI.

Adjust the path in the config, i.e. make
"KITTI_segtrack_data_dir": "/globalwork/krause/data/KITTI_MOTS/train/",
point to your own copy of the dataset and
"load_init": "/globalwork/krause/pretrained_models/tensorpack/PReMVOS-COCO-Mapillary-PreProcForKITTISegtrack/converted",
point to your copy of the pre-trained model you downloaded

Once you got KITTI working, you can create your own dataset in the same format as KITTI MOTS and then point "KITTI_segtrack_data_dir" to your own dataset instead.

**Comment by kliao4243** [comment]
> Hi, do you know to do it? I want to test my own dataset, @kliao4243

Hi, yes, I successfully tested on MOTS datasets. There are three things I did:
1. changed "MOTS_segtrack_data_dir" in configs/conv3d_sep2 to my testing data directory
2. changed DEFAULT_PATH in MOTS_segtrack_feed.py file to my testing data directory
3. made sure that the path returned by "def get_filenames_for_video_idx(self, idx)" in MOTS_segtrack_feed.py is the same as the complete path of my testing dataset.

**Comment by kliao4243** [comment]
> Please first try to get it running on KITTI.
> 
> Adjust the path in the config, i.e. make
> "KITTI_segtrack_data_dir": "/globalwork/krause/data/KITTI_MOTS/train/",
> point to your own copy of the dataset and
> "load_init": "/globalwork/krause/pretrained_models/tensorpack/PReMVOS-COCO-Mapillary-PreProcForKITTISegtrack/converted",
> point to your copy of the pre-trained model you downloaded
> 
> Once you got KITTI working, you can create your own dataset in the same format as KITTI MOTS and then point "KITTI_segtrack_data_dir" to your own dataset instead.

Thank you so much for your reply. Another question is, if I need to train on new data in MOTS format, where should I put the ground truth .txt file?

**Comment by pvoigtlaender** [comment]
if your data is in
/.../you_dataset/train/
then put images into
/.../you_dataset/train/images/
and txt groundtruth into
/.../you_dataset/train/instances_txt/

**Comment by kliao4243** [comment]
> if your data is in
> /.../you_dataset/train/
> then put images into
> /.../you_dataset/train/images/
> and txt groundtruth into
> /.../you_dataset/train/instances_txt/

Thank you. I think that's what I did, and I used the command 

python3 main.py configs/conv3d_sep2 "{\"dataset\":\"KITTI_segtrack_feed\", \"video_tags_to_load\":[\"0002\"]}"

to train. However, I always get the traceback:

"/network/FasterRCNN.py", line 260, in _create_heads
    gt_boxes = self.network_input_dict[DataKeys.BBOXES_x0y0x1y1]
KeyError: 'bboxes_x0y0x1y1'

Have you ever seen this before? Is it because I also need to modify the path in KITTI_segtrack_bbox.py? 

Thank you so much.

**Comment by ahnonay** [comment]
Hey! The KITTI_segtrack_feed dataset class is used for testing, not for training. For training, use KITTI_segtrack.
As Paul has already mentioned, you also need to modify KITTI_segtrack_data_dir if you want to work with your own dataset.

**Comment by mlyarthur** [comment]
~

**Comment by zcunyi** [comment]
> 2\. MOTS_segtrack_feed.py

where is the MOTS_segtrack_feed.py ?

**Comment by pvoigtlaender** [comment]
You find it at
datasets/MOT/segtrack/MOTS_segtrack_feed.py
https://github.com/VisualComputingInstitute/TrackR-CNN/blob/master/datasets/MOT/segtrack/MOTS_segtrack_feed.py

**Comment by zcunyi** [comment]
> You find it at
> datasets/MOT/segtrack/MOTS_segtrack_feed.py
> https://github.com/VisualComputingInstitute/TrackR-CNN/blob/master/datasets/MOT/segtrack/MOTS_segtrack_feed.py
@pvoigtlaender 
thank you. if I want  to test my data with the pretrained model, must I download the KITTI datasets?

**Comment by zcunyi** [comment]
> > Hi, do you know to do it? I want to test my own dataset, @kliao4243
> 
> Hi, yes, I successfully tested on MOTS datasets. There are three things I did:
> 
> 1. changed "MOTS_segtrack_data_dir" in configs/conv3d_sep2 to my testing data directory
> 2. changed DEFAULT_PATH in MOTS_segtrack_feed.py file to my testing data directory
> 3. made sure that the path returned by "def get_filenames_for_video_idx(self, idx)" in MOTS_segtrack_feed.py is the same as the complete path of my testing dataset.
@kliao4243 Have you finished the test on your own data with the pretrained model?

**Comment by ahnonay** [comment]
> thank you. if I want to test my data with the pretrained model, must I download the KITTI datasets?

No. However, it will be easiest to test with your own data if you first get KITTI MOTS running and then exactly imitate the folder structure and data format from that dataset.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
