### ISSUE TITLE
Question about loss when train

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#100]
Hi, I found when train there are only one loss value, like `4/5752 {loss:0.13315} elapsed 1.3235564`.
I think there are at least four loss in mask generation, boxes regression, classification, association embedding branches.
I'm confused that the relationship between the loss printed in training and the loss of the four branch.

**Comment by pvoigtlaender** [comment]
Hi, the loss printed is the sum of all components of the loss. The individual losses are at the moment not written out, but you can change the code to do so if you want to see them.

**Comment by LiXm1002** [comment]
Thank you for your reply.

**Comment by LiXm1002** [comment]
Hi，I have another question, the size of my input images is 640*480, if `resize_mode_train` set as `resize_min_short_edge_max_long_edge`, and what is the size of feature maps when feeding in ResNet?

**Comment by pvoigtlaender** [comment]
Hi,

when you specify the mode resize_min_short_edge_max_long_edge then the input size (list of two values [x, y]) will be interpreted as follows: the shorter side (i.e. 480 in your case) will be rescaled to x, and the larger side will be rescaled accordingly by keeping the aspect ratio. However, if this process would increase the larger side (i.e. 640) to more than y, then instead the resizing is only done such that the larger side will have size y.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
