### ISSUE TITLE
Issue while testing images: KITTI

### ISSUE THREAD

**Issue by chandailrc** [VisualComputingInstitute/TrackR-CNN#108]
Hi,

Thank you for your great work and sharing it. I have tried to train/test the code on my custom dataset. As per your indications I altered my dataset to look similar to the KITTI segtrack dataset.

This is what I have done so far:
1. Downloaded and trained the network on the "data_tracking_image_2" and used the commands in the "**Forwarding and Tracking**" section to visualize the results [Successful]
2. Created my own custom dataset similar to the "data_tracking_image_2" dataset and trained the network on it. [Successful]
3. Ran the training data through the custom trained model from (2) using the commands mentioned in "Forwarding and Tracking" section. [Successful - able to view the visualizations] 
4. Ran custom test data (images similar to the training data but without "instances" ground truth) through the model trained in (2) [**Unsuccessful** - detections generated but the visualization fails]

I am able to generate detections using the custom test data (4200 images) using the command:
`"python main.py configs/custom_model "{\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,\"video_tags_to_load\":[\"0000\"]}""`

However, when I try to generate the _visualizations_ and _tracking_data_ using the command below, it fails:
`python main.py configs/custom_model "{\"build_networks\":false,\"import_detections\":true,\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"do_tracking\":true,\"visualize_detections\":false,\"visualize_tracks\":false,\"load_epoch_no\":5,\"video_tags_to_load\":[\"0000\"]}"`

"0000" is the folder in my "TrackR-CNN/data/train/images/" directory

What I see at the end is:
```
...
Instructions for updating:
Colocations handled automatically by placer.
creating testnet...
starting from epoch 6
done
Forwarding video...
0000
Loading forwarded detections from file...
Done.
Loading images for visualization...
Killed
```
Can anyone help as to why the custom test data is failing on the visualization step even when it had no issues going through generating detections?

**Comment by ahnonay** [comment]
The "Killed" message probably means there was some kind of exception that is not getting printed. Difficult to tell what went wrong, unfortunately. Have you tried running the command with a debugger, e.g. in PyCharm? This should give a better idea of where things are failing.

**Comment by ahnonay** [comment]
Also, it might help to disable the visualization options in TrackR-CNN and try to produce the visualizations with mots-tools instead

**Comment by chandailrc** [comment]
Hello ahnonay! Thanks for your reply.

I did a bit more testing. I haven't been able to figure out exactly why but if I just reduce the number of test files in the directory i.e. from 4200 to ~1000, it works just fine! 

I am not really sure what to make of it though...

**Comment by ahnonay** [comment]
Hey, thanks for letting us know about this workaround! We never tested this with such long sequences. Perhaps there is not enough RAM to handle so many inputs. I'll close the issue for now, please reopen if needed.
