### ISSUE TITLE
Meeting a lot of problem  when testing data.

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#11]
Hi,everyone, I'm new in Multi-Object tracking and  I want test one of MOT17 data(such as MOT17-01-DPM in test),I meet a lot of problem.
1. I just use  000001.jpg, 000002.jpg,..... in MOT17-01-DPM/img1, is this ok? Do I still need to do something else with the dataset?
2. Where I set the test data file path ，I can't find it.
3. python main.py configs/conv3d_sep2 "{\"task\":\"forward_tracking\",\"dataset\":\"MOTS_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,\"video_tags_to_load\":[\"MOT17-01-DPM\"]}", Is there any problem in this command? And what does "video_tags_to_load" use for?
I have been confused for many days, I sincerely hope that someone can answer my question.
Thanks very much.

**Comment by kishan2110** [comment]
hi, i am done mot this working perfect.
1. 000001.jpg, 000002.jpg,..... in MOT17-01-DPM/img1 this format is working perfect no need to change.
2.  
 TrackR-CNN/datasets/MOT/segtrack/MOTS_segtrack_feed.py  change this file 
and set DEFAULT_PATH as your dataset test path
```
import glob
from datasets.Loader import register_dataset
from datasets.KITTI.segtrack.KITTI_segtrack_feed import KittiSegtrackLikeFeedDataset

NAME = "MOTS_segtrack_feed"
DEFAULT_PATH =  "mot17/test"

SEQ_IDS_TRAIN = []
SEQ_IDS_VAL = ["%04d" % idx for idx in [2, 5, 9, 11]]


@register_dataset(NAME)
class MOTSSegtrackFeedDataset(KittiSegtrackLikeFeedDataset):
  def __init__(self, config, subset):
    super().__init__(config, subset, "MOTS_segtrack", DEFAULT_PATH, SEQ_IDS_TRAIN, SEQ_IDS_VAL, False)
    self.time_starts_at_1 = True

  def get_filenames_for_video_idx(self, idx):
    return sorted(glob.glob(self.data_dir + self._video_tags[idx] +"/img1"+ "/*.jpg"))
```

3. change python main.py configs/conv3d_sep2 "{"task":"forward_tracking","dataset":"MOTS_segtrack_feed","load_epoch_no":5,"batch_size":5,"export_detections":true,"do_tracking":false,"MOTS_segtrack_data_dir": "path/to/mot/test","video_tags_to_load":["MOT17-01-DPM"]}" 
@LiXm1002

**Comment by kliao4243** [comment]
> hi, i am done mot this working perfect.
> 
> 1. 000001.jpg, 000002.jpg,..... in MOT17-01-DPM/img1 this format is working perfect no need to change.
> 
> TrackR-CNN/datasets/MOT/segtrack/MOTS_segtrack_feed.py change this file
> and set DEFAULT_PATH as your dataset test path
> 
> ```
> import glob
> from datasets.Loader import register_dataset
> from datasets.KITTI.segtrack.KITTI_segtrack_feed import KittiSegtrackLikeFeedDataset
> 
> NAME = "MOTS_segtrack_feed"
> DEFAULT_PATH =  "mot17/test"
> 
> SEQ_IDS_TRAIN = []
> SEQ_IDS_VAL = ["%04d" % idx for idx in [2, 5, 9, 11]]
> 
> 
> @register_dataset(NAME)
> class MOTSSegtrackFeedDataset(KittiSegtrackLikeFeedDataset):
>   def __init__(self, config, subset):
>     super().__init__(config, subset, "MOTS_segtrack", DEFAULT_PATH, SEQ_IDS_TRAIN, SEQ_IDS_VAL, False)
>     self.time_starts_at_1 = True
> 
>   def get_filenames_for_video_idx(self, idx):
>     return sorted(glob.glob(self.data_dir + self._video_tags[idx] +"/img1"+ "/*.jpg"))
> ```
> 
> 1. python main.py configs/conv3d_sep2 "{"task":"forward_tracking","dataset":"MOTS_segtrack_feed","load_epoch_no":5,"batch_size":5,"export_detections":true,"do_tracking":false,"video_tags_to_load":["MOT17-01-DPM"]}" here no need to change ..
>    @LiXm1002

Hi,

Thank you for sharing! I repeated your steps but the detection results txt file was still empty. Did you modify the config file? Where did you put MOT datasets and did you use the relative path of the dataset directory?

Thank you so much.

**Comment by kishan2110** [comment]
my dataset path like
mot17/
  ->train
  ->test
     ->MOT17-01-DPM
        ->img1

dataset folder mot17 is in TrackR-CNN so not require whole path so i am give only mot17/test in DEFAULT_PATH in TrackR-CNN/datasets/MOT/segtrack/MOTS_segtrack_feed.py


@kliao4243

**Comment by kliao4243** [comment]
> my dataset path like
> mot17/
> ->train
> ->test
> ->MOT17-01-DPM
> ->img1
> 
> dataset folder mot17 is in TrackR-CNN so not require whole path so i am give only mot17/test in DEFAULT_PATH in TrackR-CNN/datasets/MOT/segtrack/MOTS_segtrack_feed.py
> 
> @kliao4243

Thank you so much. Do you mean that the path is "TrackR-CNN/mot17/test/MOT17-01-DPM/img1"? Mine still does not work...

**Comment by kishan2110** [comment]
if this "TrackR-CNN/test/MOT17-01-DPM/img1" is your dataset path then give DEFAULT_PATH =TrackR-CNN/test/ and "video_tags_to_load":["MOT17-01-DPM"]

@kliao4243

**Comment by kishan2110** [comment]
sorry @kliao4243   it's my mistake  change config file "MOTS_segtrack_data_dir": "TrackR-CNN/test/"
@kliao4243

**Comment by LiXm1002** [comment]
@kishan2110 Thank you for your help, I can already test it.

**Comment by lipeng-gu** [comment]
> hi, i am done mot this working perfect.
> 
> 1. 000001.jpg, 000002.jpg,..... in MOT17-01-DPM/img1 this format is working perfect no need to change.
> 
> TrackR-CNN/datasets/MOT/segtrack/MOTS_segtrack_feed.py change this file
> and set DEFAULT_PATH as your dataset test path
> 
> ```
> import glob
> from datasets.Loader import register_dataset
> from datasets.KITTI.segtrack.KITTI_segtrack_feed import KittiSegtrackLikeFeedDataset
> 
> NAME = "MOTS_segtrack_feed"
> DEFAULT_PATH =  "mot17/test"
> 
> SEQ_IDS_TRAIN = []
> SEQ_IDS_VAL = ["%04d" % idx for idx in [2, 5, 9, 11]]
> 
> 
> @register_dataset(NAME)
> class MOTSSegtrackFeedDataset(KittiSegtrackLikeFeedDataset):
>   def __init__(self, config, subset):
>     super().__init__(config, subset, "MOTS_segtrack", DEFAULT_PATH, SEQ_IDS_TRAIN, SEQ_IDS_VAL, False)
>     self.time_starts_at_1 = True
> 
>   def get_filenames_for_video_idx(self, idx):
>     return sorted(glob.glob(self.data_dir + self._video_tags[idx] +"/img1"+ "/*.jpg"))
> ```
> 
> 1. change python main.py configs/conv3d_sep2 "{"task":"forward_tracking","dataset":"MOTS_segtrack_feed","load_epoch_no":5,"batch_size":5,"export_detections":true,"do_tracking":false,"MOTS_segtrack_data_dir": "path/to/mot/test","video_tags_to_load":["MOT17-01-DPM"]}"
>    @LiXm1002

python scripts/eval/segtrack_tune_experiment.py /path/to/detections/ /path/to/groundtruth/ /path/to/precomputed_optical_flow/ /path/to/output_file /path/to/tmp_folder/ /path/to/mots_eval/ association_type num_iterations
hello, i want to ask you for help. can you tell me that what your paths "/path/to/detections/ /path/to/groundtruth/ /path/to/precomputed_optical_flow/ /path/to/output_file /path/to/tmp_folder/ /path/to/mots_eval/ association_type num_iterations" are?
Thank you so much!

**Comment by ahnonay** [comment]
Hey, thanks for your discussion! Unfortunately, it is very hard to track who is getting which errors in this thread, so I'll close this for now. Please open a new issue with your exact problem description, if something still doesnt work.

**Comment by EchoAmor** [comment]
@kishan2110  Hello! Thanks for sharing ! I followed your steps,but I got the error:

> Traceback (most recent call last):
  File "/home/echo/a_project/TrackR-CNN/main.py", line 39, in <module>
    tf.app.run(main)
  File "/home/echo/anaconda3/envs/MOTS/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/echo/a_project/TrackR-CNN/main.py", line 22, in main
    assert os.path.exists(config_path), config_path
AssertionError: {"task":"forward_tracking","dataset":"MOTS_segtrack_feed","load_epoch_no":5,"batch_size":5,"export_detections":true,"do_tracking":false,MOTS_segtrack_data_dir: /home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/,"video_tags_to_load":[MOT17-12-SDP]}


DO you know how to solve this problem? @LiXm1002

**Comment by ahnonay** [comment]
Please do not ask new questions in closed issues. Open a new issue instead if needed.

(It looks like you submitted the "{"task":"forward_tracking",......" string as the only argument to main.py. You also need to give a config file as argument.)
