### ISSUE TITLE
Meeting a  problem when tuning

### ISSUE THREAD

**Issue by YanruH18** [VisualComputingInstitute/TrackR-CNN#12]
Hello, thank you for your sharing!

When I run tuning, I found there was something unclear in README.
![图片](https://user-images.githubusercontent.com/49109560/60888225-df78d200-a288-11e9-8f3f-25af1a435aeb.png)
![图片](https://user-images.githubusercontent.com/49109560/60888330-1b139c00-a289-11e9-9d2c-ebc26cb01915.png)
Could you explain these paths more in detail?
@pvoigtlaender

**Comment by YanruH18** [comment]
I also found this problem:
![image](https://user-images.githubusercontent.com/49109560/61351424-40ae3000-a89d-11e9-9ccd-ea0c2fb6a138.png)
It seems like the split way of "results" in read_result function has some problems, and it can not match the expected values:
![image](https://user-images.githubusercontent.com/49109560/61351650-d944b000-a89d-11e9-9b27-08e32f7f3983.png)
My "content" is like this:
![image](https://user-images.githubusercontent.com/49109560/61351736-19a42e00-a89e-11e9-8339-ab363c9e505e.png)
![image](https://user-images.githubusercontent.com/49109560/61351752-2759b380-a89e-11e9-99a6-078e89196bd2.png)
I wonder why this happens. Hope you could help me, thank you !
@pvoigtlaender

**Comment by lipeng-gu** [comment]
> Hello, thank you for your sharing!
> 
> When I run tuning, I found there was something unclear in README.
> ![图片](https://user-images.githubusercontent.com/49109560/60888225-df78d200-a288-11e9-8f3f-25af1a435aeb.png)
> ![图片](https://user-images.githubusercontent.com/49109560/60888330-1b139c00-a289-11e9-9d2c-ebc26cb01915.png)
> Could you explain these paths more in detail?
> @pvoigtlaender

i meet the same problems when tuning. have you solved these problems? do you can contact with me by my email 854215068@qq.com

**Comment by ahnonay** [comment]
Hey!
Sorry for the confusion, I will update the Readme with the following information:

`/path/to/groundtruth/ ` refers to the `instances` or `instances_txt` folder containing the annotations (which you can download from the project website). `/path/to/precomputed_optical_flow` can usually be set to a dummy folder; it refers to optical flow for input images, which is used only for a few of the ablation experiments in the paper (namely when setting `association_type` to `mask` or `bbox_iou`; if you set that to something else, than this path is ignored). At `/path/to/output_file`, a file will be created containing the results of the individual tuning iterations, please make sure this path is writable. At `/path/to/tmp_folder` a lot of intermediate folders will be stored, you can delete these afterwards.

Regarding the error you were getting: We changed some things before publishing the code and seem to have missed this, sorry! Will fix this.

**Comment by ahnonay** [comment]
Fixed in commit 83be5354dca30c5d4f2eefc51d9ae4425ef1677b

**Comment by SamihaSara** [comment]
> Hey!
> Sorry for the confusion, I will update the Readme with the following information:
> 
> `/path/to/groundtruth/ ` refers to the `instances` or `instances_txt` folder containing the annotations (which you can download from the project website). `/path/to/precomputed_optical_flow` can usually be set to a dummy folder; it refers to optical flow for input images, which is used only for a few of the ablation experiments in the paper (namely when setting `association_type` to `mask` or `bbox_iou`; if you set that to something else, than this path is ignored). At `/path/to/output_file`, a file will be created containing the results of the individual tuning iterations, please make sure this path is writable. At `/path/to/tmp_folder` a lot of intermediate folders will be stored, you can delete these afterwards.
> 
> Regarding the error you were getting: We changed some things before publishing the code and seem to have missed this, sorry! Will fix this.

@ahnonay If I set  `association_type` to `mask` or `bbox_iou` then what should be put in `/path/to/precomputed_optical_flow`?

**Comment by ahnonay** [comment]
You'll need to manually compute optical flow for the images in the datasets (e.g. using something like FlowNet). Then you need to put it into the file format we use for optical flow, which is unfortunately kind of undocumented... Check load_optical_flow,  open_flow_png_file in TrackingForwarder_util.py. Please contact Paul if you really need to use optical flow based tracking, he may still have some precomputed files.

**Comment by jong372** [comment]
@SamihaSara were you able to implement the optical flow into TrackR-CNN? Thanks in advance!

**Comment by SamihaSara** [comment]
@jong372 no I am stuck with some other experiments on TrackRCNN, did not email Paul for the pre-computer files. Sorry for not being able to help you.
