### ISSUE TITLE
how to decide threshold?

### ISSUE THREAD

**Issue by kishan2110** [VisualComputingInstitute/TrackR-CNN#13]
hello, Thanks for sharing.
I try to train my own datasets. training is done perfect. its also give good loss, but in prediction part i am confuse to set threshold because in my dataset classes are different. they are not car or pedestrian. so how can i decide threshold? 
@pvoigtlaender

**Comment by pvoigtlaender** [comment]
Hi,

I assume you're talking about the detection confidence threshold. Essentially it's trial and error, so either make some visualizations with a small threshold and then look at what a good cutoff would be or you can try different values and evaluate it quantitatively.

**Comment by kishan2110** [comment]
okay,thank you!!
@pvoigtlaender
