### ISSUE TITLE
Problem about ground truth picture in instances

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#14]
I download both .png and .txt format of ground truth of annotations,but I am confused about the .png format annotation.First ,I find human shadow in picture and a lot of brighter rectangle in picture too ,what is this rectangle? Second, if using .png format annotation,when I label a person in frame T and the same person in frame T+1, How to label the two instance annotations for the same ID. How is this information reflected in the picture?

I hope someone can solve my confusion，Thanks.

**Comment by pvoigtlaender** [comment]
Hi,

the format is described at https://www.vision.rwth-aachen.de/page/mots
Also, it might be easier to work with the text format instead (and you can convert to png later if necessary).
The brighter rectangles are ignore regions. The pngs are not really intended to be looked at by humans.
For frame consistency just label the instance with the same value.

**Comment by LiXm1002** [comment]
Wow, that is, the same instance between two frames has the same pixel value, different instances of the same frame have different pixel values.

**Comment by ahnonay** [comment]
Yes. Please reopen if there are more questions.
