### ISSUE TITLE
Loading image issues

### ISSUE THREAD

**Issue by GehenHe** [VisualComputingInstitute/TrackR-CNN#15]
Hi, thank you for sharing your source code.
I met some issues when I tried to inference tracking result on the KITTI dataset.
I met issues with the following steps:
1) Configuring `load_init` and `KITTI_segtrack_data_dir` in `configs/conv3d_sep2`: 

> "load_init": "/home/gehen/PycharmProjects/MOTS/TrackR-CNN/models/trackrcnn_init",
"KITTI_segtrack_data_dir": "/home/gehen/Downloads/images/tracking/MOTS/KITTY/training/image_02/",

2) Configuring `DEFAULT_PATH` in `datasets/KITTI/segtrack/KITTI_segtrack.py` as described in [](url): https://github.com/VisualComputingInstitute/TrackR-CNN/issues/4

> DEFAULT_PATH = "/home/gehen/Downloads/images/tracking/MOTS/KITTY/training/image_02/"

3) Copying [provided detections](https://www.vision.rwth-aachen.de/media/resource_files/trackrcnn_detections.zip) to `forwarded/con3d_sep2/detections/5`.

4) Run `python main.py configs/conv3d_sep2"{\"build_networks\":false,\"import_detections\":true,\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"do_tracking\":true,\"visualize_detections\":true,\"visualize_tracks\":false,\"load_epoch_no\":5,\"video_tags_to_load\":[\"0002\",\"0006\",\"0007\",\"0008\",\"0010\",\"0013\",\"0014\",\"0016\",\"0018\"]}"`

5) Though obtaining tracking results in `forwarded/con3d_sep2/tracking_data`, but all the visualization failed, which reports `assert len(det_boxes) == len(imgs)`.

where the `imgs` is an empty list.
It seems that the tracker cannot load images in the inference, and remains an empty image list in the visualization.

What might be the problem that fails the tracker in loading images? Moreover, the tracker also fails to generate detection results in step (3) with the empty image list.

**Comment by hks5201106166** [comment]
put the KITTI instances into the training dir

**Comment by ahnonay** [comment]
I have clarified the Readme on how to setup the dataset. Put the images into a folder /path/to/kitti_mots/images and the annotations into a folder /path/to/kitti_mots/instances

Please reopen in case of more questions
