### ISSUE TITLE
Meeting some problem when tuning

### ISSUE THREAD

**Issue by lipeng-gu** [VisualComputingInstitute/TrackR-CNN#17]
Hello, thank you for your sharing!
When I try to run tuning, I found there was something unclear in README.
/path/to/precomputed_optical_flow/ 
/path/to/output_file 
/path/to/tmp_folder/ 
/path/to/mots_eval/ 
association_type 
num_iterations
Could you explain these paths more in detail?
thank you, very much!

**Comment by ahnonay** [comment]
Hey!
Sorry for the missing explanation! I have updated the Readme with more information, see also issue #12 . In addition, `association_type` should be ´reid´ and ´num_iterations´ should be ´1000´ to have the default configuration from the paper. For ´/path/to/mots_eval´, check out the mots_eval repository and supply the path here.

Please reopen if there are further questions.
