### ISSUE TITLE
How to set the file path, and dataset path?

### ISSUE THREAD

**Issue by Vankeee** [VisualComputingInstitute/TrackR-CNN#18]
Sorry, I got some very basic questions here. It's about the configration of this project. I read the readme, but still got these quetions.
In the config file, the MOT path is   "MOTS_segtrack_data_dir":"/globalwork/krause/data/MOTS_challenge/train/".
The downloaded dataset is MOT17. Should I just put the train and test folder into MOTS_challenge?
And where should I put the trackrcnn_init folder into?  If I use the MOT dataset, where should I put the following data into?

Images (hosted on original MOTChallenge webpage)
Annotations in png format
Annotations in txt format
TrackR-CNN detections

**Comment by Vankeee** [comment]
Here is what I do to run the code to test:
①In configs/sconv3d_sep2 file, change the value of key task, train_no_val with forward_tracking.
Change the value of key dataset, KITTI_segtrack with MOTS_segtrack_feed(Cause I use MOT data)
②In  configs/sconv3d_sep2 add the key:value,  "video_tags_to_load" : ["MOT17-01-DPM"]
③In configs/conv3d_seq2, change the value of key MOTS_segtrack_data_dir to "./data/MOTS_challenge/test/"(Because I put the data in the test)
④Put these three model files conv3d_sep2-00000005.data-00000-of-00001， conv3d_sep2-00000005.index， 
conv3d_sep2-00000005.meta in to models/conv3d_sep2
⑤ Put the test data.The data path is /TrackR-CNN-master/data/MOTS_challenge/test/MOT17-01-DPM
⑥ In MOTS_segtrack_feed.py file, in function def get_filenames_for_video_idx(self, idx), change the  path of return value.
"return sorted(glob.glob(self.data_dir + self._video_tags[idx] + "/img1/" + "/*.jpg")) "
⑦ in the command line, run python main.py configs/conv3d_sep2

**Comment by qingchunlizhi** [comment]
Excuse, me! I am troubled by the train mode.how to train mot17 data using this model? What is the file tree? Thank you!!!

**Comment by pvoigtlaender** [comment]
.../MOTS_challenge/train/
   images/
   instances/
   instances_txt/

where you only need one of instances and instances_txt

Images for example:
.../MOTS_challenge/train/images/0005/*.jpg

instances for example
.../MOTS_challenge/train/instances/0005/*.png

instances_txt:
.../MOTS_challenge/train/instances_txt/0005.txt

**Comment by ahnonay** [comment]
> Excuse, me! I am troubled by the train mode.how to train mot17 data using this model?
You cannot train TrackR-CNN on MOT17, because it lacks segmentation mask annotations. However, you can train on MOTS Challenge, see the project [page](https://www.vision.rwth-aachen.de/page/mots)

Please reopen in case of more questions.
