### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor with shape[772,28,28,1024]

### ISSUE THREAD

**Issue by lcyawym** [VisualComputingInstitute/TrackR-CNN#21]
Can you tell me your computer setup？
When I run the test result using MOT17，It display ResourceExhaustedError: OOM when allocating tensor with shape[772,28,28,1024]

**Comment by pvoigtlaender** [comment]
We usually use NVIDIA 1080 TI with 11 GB of memory. For MOTChallenge (i.e. MOT17) inference, we changed the resize settings to

  "resize_mode_val": "resize_min_short_edge_max_long_edge",
  "input_size_val": [540, 1024],

**Comment by lcyawym** [comment]
Thank you for your reply！I will try it again.

**Comment by lcyawym** [comment]
Hello, I want to test my own dataset. In addition to pictures.Do I still need to provide something else? I use the command to generate detections. But the detections files is empty
python main.py configs/conv3d_sep2 "{\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,\"video_tags_to_load\":[\"01\"]}"

**Comment by LiXm1002** [comment]
@pvoigtlaender Hi,I have met this question too when training.
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[80,7,7,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Do you konw which parameters should I modify?
Thanks.

**Comment by pvoigtlaender** [comment]
You can save memory by reducing the size. If you're talking about inference, then change
"input_size_val": [540, 1024], to a smaller value
otherwise change the correponding train value
input_size_train.
This might however affect results!

**Comment by lcyawym** [comment]
@pvoigtlaender  hello， if I want to train the network on other dataset. I just need to  make the dataset like kitti mots? In the paper,I saw that the resnet is pre-trained on some dataset.Shall I need to train resnet?

**Comment by pvoigtlaender** [comment]
You can use this pre-trained model (pre-trained first on ImageNet, then COCO, then Mapillary I think):
https://omnomnom.vision.rwth-aachen.de/data/trackrcnn/trackrcnn_init.zip
specify that with "load_init" in the config
or alternatively just start from the KITTI checkpoint

**Comment by LiXm1002** [comment]
@pvoigtlaender  Thanks,I will try it again.

**Comment by lcyawym** [comment]
@pvoigtlaender  thanks for  your reply.And anoyther problem,can you tell before you train your model, how to get the annotations of MOTChallenge's data?  I fine that mot_tools has tools to product instances files.

**Comment by lcyawym** [comment]
And if i want to use other open dataset. I need to use labelme to annotation the dataset?

**Comment by ahnonay** [comment]
I'm not sure I understood your questions. To get the annotations for the MOTSChallenge dataset (which contains sequences from MOTChallenge), please look at the [project page](https://www.vision.rwth-aachen.de/page/mots). If you want to train on another dataset, you need to create annotations in the same format as KITTI MOTS and MOTSChallenge (the format is also explained on the project page).

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
