### ISSUE TITLE
A bug when training with MOTSchallenge dataset

### ISSUE THREAD

**Issue by ifzhang** [VisualComputingInstitute/TrackR-CNN#24]
I trained the model on MOTSchallenge dataset and test the model with my own videos. However, the model detected cars in my video and recognize them as pedestrians. I do not want to detect cars, just pedestrians. So how can I do that? Thank you!

**Comment by pvoigtlaender** [comment]
Hi,

we'll need some more details to diagnose it. Maybe it's a problem with the class mapping? Does it then also detect pedestrians and maybe label them as cars, so it's just flipped?

**Comment by ifzhang** [comment]
Pedestrians are detected and recognized correctly. I just use MOTSchallenge dataset to train my model, not using KITTI. I find there are some cars in MOTSchallenge 0005 sequence. Is it possible that these cars are labelled as pedestrians in the instances_txt folder? I think there is only one pedestrians class in MOTSchallenge dataset. So it's very strange that I can detect cars in my own test videos.

**Comment by pvoigtlaender** [comment]
I think we had seen a similar case before. @ahnonay can you comment on that?

**Comment by ahnonay** [comment]
No, any cars in MOTSChallenge are simply not labelled. Unfortunately, I cannot say from the description, why this error occurs. Maybe there is too large of a domain shift between MOTSChallenge and your dataset? You could try training on some of your own data.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
