### ISSUE TITLE
Problem when testing on my own data

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#25]
@pvoigtlaender Hi, I have made a data set  for hundreds pictures. And I have train for two days. When I test the picture in train data set, It works well. But when I test images not in train data sets,I met a lot of problem . The result of testing the image is no longer the original order. 
e.g. the image 000037.jpg in forwarded/conv3d_sep2/vis/tracks/0000 folder is different from 000037.png in dataset/test/0000 folder(My test data path),Is this normal?
When testing,is this network reading pictures sequentially? or it is up to the network itself to decide which is the next frame?
I hope you can help me solve my confusion.

**Comment by pvoigtlaender** [comment]
It's supposed to read in order, not sure what is happening there.

**Comment by LiXm1002** [comment]
Oh, thank you, I will try again to find the reason.

**Comment by LiXm1002** [comment]
The problem was found. It‘s my carelessness. I mistakenly wrote 000000.png as 00000.png(The first ten pictures are all forrgotten zero), which caused the order to be wrong.
