### ISSUE TITLE
problem for testing  results with  MOTS_challenge datasets  

### ISSUE THREAD

**Issue by mlyarthur** [VisualComputingInstitute/TrackR-CNN#27]
![000000](https://user-images.githubusercontent.com/29242717/64020210-96941a00-cb63-11e9-9087-aa4d6bb21fbf.jpg)
when I want to visualize  the  semantic result of detection, it does not  match the original people outlines, I want to know if there is any setting  incorrect in config/conv3d_sep2

**Comment by mlyarthur** [comment]
![000006](https://user-images.githubusercontent.com/29242717/64020493-4bc6d200-cb64-11e9-9f2d-e83436af6cce.jpg)

**Comment by ahnonay** [comment]
It is difficult to diagnose from the pictures but have you made sure that "input_size_val" in the config has the right aspect ratio? Note that KITTI MOTS and MOTS Challenge have different aspect ratios.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
