### ISSUE TITLE
Using KITTI and MOT17 together to train my model together

### ISSUE THREAD

**Issue by ifzhang** [VisualComputingInstitute/TrackR-CNN#28]
I put the two datasets together and I want to use them all to train my model. How to set the "resize_mode_train" and "input_size_train"?

**Comment by ahnonay** [comment]
You could train on one dataset first and then on the other (with a different config). You may also try
  "resize_mode_train": "resize_min_short_edge_max_long_edge",
  "input_size_train": [400, 1024],
but I can't currently test whether that will work

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
