### ISSUE TITLE
Problem when training with multiple gpu

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#29]
When training on my own dataset and I set "gpus": 2 in conv3d_sep2,it raises ValueError.
ValueError: Index out of range using input dim 0; input has only 0 dims for 'trainnet/strided_slice_10' (op: 'StridedSlice') with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.
But when setting "gpus": 1 ,it works well.
If I want to use multiple GPU training, do I need to modify other parameters?

**Comment by ahnonay** [comment]
Multi-gpu training with TrackR-CNN is not supported. We produced all results using a single gpu. It may work if you try setting "own_dataset_per_gpu": true.

**Comment by LiXm1002** [comment]
Thanks,I will try it later.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
