### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jackkwok** [VisualComputingInstitute/TrackR-CNN#3]
Thanks for providing the code on github.  Can you please add a license?

**Comment by pvoigtlaender** [comment]
Hi,

the README already mentioned MIT license, now I explicitly added a LICENSE file with MIT license.
Please also note that parts of the code are based on Tensorpack (https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN) and a signle file for logging is based on RETURNN (https://github.com/rwth-i6/returnn/blob/master/Log.py).
