### ISSUE TITLE
where to find the results and to visualize them

### ISSUE THREAD

**Issue by EchoAmor** [VisualComputingInstitute/TrackR-CNN#31]
Thanks for your work!
I have run the code successfully I think ,

`Forwarding video...
0018
Loading forwarded detections from file...
Done.
Loading images for visualization...
Done.
Time for tracking (s): 6.499499977508094e-05 FPS for tracking including forwarding: 0.0
Exporting tracking results
Visualizing tracks
Time for forwarding (s): 0.0002299799998581875 FPS for forwarding (wo. tracking): 0.0

Process finished with exit code 0`

BUT where to find the results? And how can I visulize the results, I dont know ,it will help me a lot if you can tell me,thanks!

**Comment by pvoigtlaender** [comment]
There should be a folder TrackR-CNN/forwarded/... in which you can find the results.
For visualization, use the mots tools https://github.com/VisualComputingInstitute/mots_tools

**Comment by EchoAmor** [comment]
Thanks！I have found the results,**_detections_** and **_tracking_data_**.
Then I want to visualize the results,following the readme , run the commands

> python mots_eval/visualize_mots.py tracking_results img_folder output_folder seqmap

The **_tracking_results_** == /TrackR-CNN/forwarded/conv3d_sep2/tracking_data

But get error:

> AssertionError: Can't find data in directory /TrackR-CNN/forwarded/conv3d_sep2/tracking_data

Do you know where the problem is?
@pvoigtlaender

**Comment by EchoAmor** [comment]
sorry, I have found the problem is  _**detections**_ and **_tracking_data_** are o bytes.
![mots1](https://user-images.githubusercontent.com/25685837/65694121-eb19af00-e0a7-11e9-8da2-6980a1e68cb1.png)
 I have read the answers you gave to others, and changed the path the right way, I don't know how can fix the problem. Do I need to do something with the datasets? I downloaded them from your page .

When I run the **_Trackrcnn_** it didn't get errors, but the results are 0 bytes. Can you help me with this ? Thanks a lot!
![mots2](https://user-images.githubusercontent.com/25685837/65694357-4ea3dc80-e0a8-11e9-8319-82bbb5b4f9e9.png)

![mots3](https://user-images.githubusercontent.com/25685837/65694389-5d8a8f00-e0a8-11e9-98ea-d0151d5a9dfe.png)

![mots4](https://user-images.githubusercontent.com/25685837/65694549-9f1b3a00-e0a8-11e9-8117-5f2559486e99.png)

@pvoigtlaender

**Comment by LiXm1002** [comment]
It seems that the network hasn't read the input images. When I testing Kitti dataset, image path is /media/ubuntu/SSD/TrackR-CNN/data/kitti_mots/train/images/0000,and the path in conv3d_sep2 is "KITTI_segtrack_data_dir": "/media/ubuntu/SSD/TrackR-CNN/data/kitti_mots/train" . It works well.

**Comment by EchoAmor** [comment]
@LiXm1002  sorry,but what is the 0000 refering to  in image path ? uh ,I only change the path in **conv3d_sep2.py**, it's "KITTI_segtrack_data_dir": "/home/echo/a_project/TrackR-CNN/kitti_mots/kitti/images/data_tracking_image_2/training"

**Comment by LiXm1002** [comment]
![Screenshot from 2019-09-27 14-06-20](https://user-images.githubusercontent.com/39939478/65745962-03351100-e130-11e9-91f5-141bc87e36ab.png)
![Screenshot from 2019-09-27 14-07-04](https://user-images.githubusercontent.com/39939478/65746016-37103680-e130-11e9-90ff-67f916c74f33.png)
Mine is like this.

**Comment by EchoAmor** [comment]
That make no sense, I have tried many times ,but the results are 0 bytes,so confused/(ㄒoㄒ)/~~

**Comment by LiXm1002** [comment]
Maybe you can try to print path of the images or some parameter information when testing.

**Comment by EchoAmor** [comment]
OK，thanks very much! I am tring

**Comment by EchoAmor** [comment]
I know the problem now...the folder must be named _**/images**_ and **_/instances_**, when I downloaded them ,the name is  _**/image_02**_  , so I ignored this !so silly error!!!
![mots6](https://user-images.githubusercontent.com/25685837/65816491-c996ff80-e22e-11e9-9935-f6d7b521897e.png)

**Comment by ahnonay** [comment]
Glad to hear you found the problem. Thanks also to @LiXm1002 ! Closing this for now, please reopen if needed
