### ISSUE TITLE
what  is KITTI_segtrack_data_dir and MOTS_segtrack_data_dir included?

### ISSUE THREAD

**Issue by yinhai86924** [VisualComputingInstitute/TrackR-CNN#32]
hello! Acording to your reademe, I download from https://www.vision.rwth-aachen.de/page/mots  so, which dir include this data?  if  I want to test this datasets, how to change dir acording to the conv3d_seq2? thank you !

**Comment by ahnonay** [comment]
You need to download the KITTI MOTS images and annotations from that website. Then you need to set up the paths correctly, as explained in the readme:

> Furthermore, you'll need the [KITTI MOTS](https://www.vision.rwth-aachen.de/page/mots) dataset, where we assume you have a folder /path/to/kitti_mots with subfolders /path/to/kitti_mots/images containing the input images (i.e. there exist subfolders /path/to/kitti_mots/images/0000, /path/to/kitti_mots/images/0001, ...) and /path/to/kitti_mots/instances  (again with subfolders 0000, 0001, ...) containing the annotations.

Afterwards, set "KITTI_segtrack_data_dir" in configs/conv3d_sep2 to "/path/to/kitti_mots"

**Comment by ahnonay** [comment]
Closing this, please reopen if needed
