### ISSUE TITLE
A problem with train my data

### ISSUE THREAD

**Issue by lalalabiubiu** [VisualComputingInstitute/TrackR-CNN#36]
Hello, my data set is in txt format, but the code only reads png format, how should I read the data in txt format? @pvoigtlaender

**Comment by pvoigtlaender** [comment]
I think TrackR-CNN should be able to read both formats (@ahnonay can you confirm?). I think you need to put the data in a folder named instances_txt

**Comment by lalalabiubiu** [comment]
Thank you for your reply。What do you mean is that I need to put txt into the instances_txt and also need to put the png format into the instance, the original image into the images folder? But in the website：https://www.vision.rwth-aachen.de/page/mots say that txt and png can be selected one by one.. Or what part of the code do I need to modify so that TrackRCNN can read the data in txt format?

**Comment by pvoigtlaender** [comment]
There should be no need to change code.
And you need only either png format Annotations or txt format Annotations.
If you use png Annotations, they need to be in a folder named "instances". If you use txt Annotations, they need to be in a Folder named "instances_txt". Do not put Annotations (png or txt) into an images folder.
Maybe first try to use the txt Annotations of the original KITTI MOTS dataset and get it running.

**Comment by lalalabiubiu** [comment]
I have already run KITTIdata and MOTdata before, and the effect is very good, but when I train my own data, I replaced the annotation file in the instances_txt folder with my own txt and put the original image into the images folder, but It was given an error. Then I read the code, I found def read_inputfile_lists(self) in KITTI_segtrack.py: is the png in the reads, and did not find the function to read txt.
![image](https://user-images.githubusercontent.com/36154131/66307325-b96dd700-e936-11e9-84a8-9f332153aa89.png)
![image](https://user-images.githubusercontent.com/36154131/66307338-c4c10280-e936-11e9-8242-009fa5078220.png)
![image](https://user-images.githubusercontent.com/36154131/66307356-d3a7b500-e936-11e9-8950-45c52856e4b9.png)

So is there a problem with my data set? Or which other step is a problem?

**Comment by pvoigtlaender** [comment]
Oh, I think I might have been wrong and TrackR-CNN really does expect the annotations in png format.
In this case, you'll need to convert the txt format to png format. I think we do not have a script for this, because we usually first create the pngs and then convert them to txt and not the other way round.
Maybe you can take inspiration from the visualization script https://github.com/VisualComputingInstitute/mots_tools/blob/master/mots_vis/visualize_mots.py and then instead of visualizing, you create the annotation pngs (the format is briefly described at https://www.vision.rwth-aachen.de/page/mots ).

Or alternatively modify TrackR-CNN so that it can load the txt format instead of the pngs (pull request welcome).

**Comment by lalalabiubiu** [comment]
Thank you very much for your answer, I will try both of it later.

**Comment by lalalabiubiu** [comment]
Excuse me, thank you very much for your help. I have converted txt to png, and I get an 8-bit png, but trackrcnn needs a 16-bit png. When I get a 16-bit png via pypng but it is a bit different from the png you provided earlier. How do you get your png? 
Since there are two classes in my picture, I want to know how trackrcnn gets his class_id and instance_id in the case of read-only png.
This is my png8：It contains two classes, point:1, other:2, different instances have different colors
 
![image](https://user-images.githubusercontent.com/36154131/66895514-95d91980-f025-11e9-98b5-12a6fc1190cc.png)

And this is the converted png16：Without color difference, how can trackrcnn get classification information and instance information?
 
![image](https://user-images.githubusercontent.com/36154131/66895527-9d98be00-f025-11e9-9a42-d90d42c96f66.png)
 
Thank you for your  help！
@pvoigtlaender

**Comment by pvoigtlaender** [comment]
Hi,

to save the png with 16 bits, you can use
```
ann = np.zeros((h, w), dtype="uint16")
# put some data into ann
cv2.imwrite(out_filename, ann)
```

The format is described here:
https://www.vision.rwth-aachen.de/page/mots
The class id can be obtained by floor divison of the object id by 1000 (class_id = obj_id // 1000) and the instance id can be obtained by the object id modulo 1000 (instance_id = obj_id // 1000).

**Comment by lalalabiubiu** [comment]
Thank you for your reply, but there are two types of targets in the same picture. For example, if I have cars and people in my png, can their class_id be expressed with obj_id // 1000?

**Comment by lalalabiubiu** [comment]
In the absence of a label, whether the object_id of png contains category information, such as obj_id=1005 of a person in the same png and obj_id=2003 of a car.

**Comment by pvoigtlaender** [comment]
I didn't fully understand your question.
If you have two classes, then for the instances of the first class, use ids which start with 1000, e.g.
1001, 1002, 1003, ...
and for the second class use ids which start with 2000, e.g.
2001, 2002, 2003, ...
You will not be able to see the different instances when visually looking at the png (since their values are only slightly different), but you should at least be able to see 2 different classes visually and TrackR-CNN will be able to read all information including instances out of the png.

**Comment by lalalabiubiu** [comment]
I know where the problem is, Thank you!
 This is the information for your png:
  
![image](https://user-images.githubusercontent.com/36154131/66909809-fbd29a80-f03f-11e9-8886-9cb6c003887a.png)

This is my png:
   
![image](https://user-images.githubusercontent.com/36154131/66909831-042ad580-f040-11e9-84bb-a96e390e9704.png)

So, my question is how can I make my png contain obj_id  (1001, 2001)like yours

**Comment by pvoigtlaender** [comment]
```
ann = np.zeros((h, w), dtype="uint16")
# get "mask" from somewhere
ann[mask] = 1001
cv2.imwrite(out_filename, ann)
```

**Comment by lalalabiubiu** [comment]
May I ask what type of mask is it? Rle encoded string? Or uint8 png?thank you.

**Comment by pvoigtlaender** [comment]
A numpy ndarray. Since you want to fill the output png with your own data, you have to get the data from somewhere, I guess from your data in txt format, then you can decode the rle which gives you an ndarray with which you can index the array which you will later write out as png.

**Comment by lalalabiubiu** [comment]
I get it，thank you very much for your help.You are so kind！

**Comment by pvoigtlaender** [comment]
Happy to help :)
It seems to be resolved, so I'll close. If there's still trouble with the same problem, feel free to reopen. If you encounter another problem, just open another issue.

**Comment by jong372** [comment]
@lalalabiubiu did you manage to annotate your own images according to the format of TrackR-CNN (with instance id etc.)?  Thanks in advance!

**Comment by lalalabiubiu** [comment]
Yes, we successfully annotated our dataset using labelme and&nbsp;mots_tools.First of all, we use labelme to label the sample, the label are 1001,1002,1003... And then we use&nbsp;labelme_to_dataset.py to&nbsp;converting the format.When converting the format, save labels to .txt. Then modify&nbsp;mots_tools/mots_common/images_to_txt.py to&nbsp;read the PNG and txt file (labels). Finally,convert them to the format required by trackrcnn based the codes:
ann = np.zeros ((h, w), dtype="uint16")
# get "mask" from somewhere
ann[mask] = 1001
cv2.imwrite(out_ filename, ann)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualComputingInstitute/TrackR-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 晚上10:22
收件人:&nbsp;"VisualComputingInstitute/TrackR-CNN"<TrackR-CNN@noreply.github.com&gt;;
抄送:&nbsp;"雨季不再来"<1294022723@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualComputingInstitute/TrackR-CNN] A problem with train my data (#36)





 
@lalalabiubiu did you manage to annotate your own images according to the format of TrackR-CNN (with instance id etc.)?  Thanks in advance!
