### ISSUE TITLE
How to test and train on MOT dataset?

### ISSUE THREAD

**Issue by EchoAmor** [VisualComputingInstitute/TrackR-CNN#37]
I have successfully test on kitti dataset, and now I want to train and test on MOTS  dataset, I use the following commands to test on MOTS dataset,

> {\"task\":\"forward_tracking\",\"dataset\":\"MOTS_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,MOTS_segtrack_data_dir: /home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/,\"video_tags_to_load\":[MOT17-01-DPM]}"

**_But get this error,_**

>
Traceback (most recent call last):
  File "/home/echo/a_project/TrackR-CNN/main.py", line 39, in <module>
    tf.app.run(main)
  File "/home/echo/anaconda3/envs/MOTS/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/echo/a_project/TrackR-CNN/main.py", line 22, in main
    assert os.path.exists(config_path), config_path
AssertionError: {"task":"forward_tracking","dataset":"MOTS_segtrack_feed","load_epoch_no":5,"batch_size":5,"export_detections":true,"do_tracking":false,MOTS_segtrack_data_dir: /home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/,"video_tags_to_load":[MOT17-01-DPM]}

The data path in My **_config.py_**  is like this :
![mots7](https://user-images.githubusercontent.com/25685837/66395598-6f562580-ea0a-11e9-889b-9eca52e58ccf.png)
![mots8](https://user-images.githubusercontent.com/25685837/66395606-72e9ac80-ea0a-11e9-8892-0f53967dba60.png)

And this is my dataset tree:
kitti_mots/mot/mot17/test
kitti_mots/mot/mot17/train

![mots9](https://user-images.githubusercontent.com/25685837/66395960-3cf8f800-ea0b-11e9-936a-dda0dd8be1f7.png)

I don't know where the problem is ,can you help me please? Thanks a lot ! @pvoigtlaender @ahnonay

**Comment by pvoigtlaender** [comment]
The way you are running it is not correct, the first command line parameter needs to be the path to the config file. The second argument can be a dictionary which overwrites stuff from the config.

Please try like this:

``
python main.py /path/to/your/config {"task":"forward_tracking","dataset":"MOTS_segtrack_feed","load_epoch_no":5,"batch_size":5,"export_detections":true,"do_tracking":false,MOTS_segtrack_data_dir: /home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/,"video_tags_to_load":[MOT17-01-DPM]}
``

here, /path/to/your/config is something like configs/conv3_sep2

**Comment by EchoAmor** [comment]
Thanks a lot ! I have successfully run on MOTS dataset.
If I want to visualize and eval  the code on MOTS dataset,  do the commands in mots_tools need change? Is it the same as kitti dataset?  I find  there  are no examples on MOTS dataset. @pvoigtlaender @ahnonay @kishan2110

**Comment by pvoigtlaender** [comment]
It should work the same just with different paths I think, please have a try.

**Comment by EchoAmor** [comment]
I tried but failed. In TrackR-CNN project, I use the following command to test :

> configs/conv3d_sep2
{\"task\":\"forward_tracking\",\"dataset\":\"MOTS_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":true,\"MOTS_segtrack_data_dir\":\"/home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/\",\"video_tags_to_load\":[\"MOT17-01-DPM\",\"MOT17-01-FRCNN\",\"MOT17-01-SDP\",\"MOT17-03-DPM\",\"MOT17-03-FRCNN\",\"MOT17-03-SDP\"]}

It runs well and I get the results:
![mots10](https://user-images.githubusercontent.com/25685837/66562336-08fa1000-eb8e-11e9-9de9-1ca5ba9fd1db.png)

But when I want to further visualize the results , it get errors, I add  **_\"visualize_tracks\":true_** into the above commands,then get this error:
![mots11](https://user-images.githubusercontent.com/25685837/66562475-52e2f600-eb8e-11e9-9a7d-bca473a2cc41.png)

 I have changed the size 

![mots13](https://user-images.githubusercontent.com/25685837/66562530-7017c480-eb8e-11e9-929a-d6d8fb90997f.png)

BUT it still gets the error.

Then I use **_MOTS_tools_** project to do the work.
I have writen the **_test_MOTSchallenge.seqmap_** file just like **_val_MOTSchallenge.seqmap_**.
I use the following commands:

> /home/echo/a_project/TrackR-CNN/forwarded/conv3d_sep2/tracking_data/
/home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/MOT17-01-DPM/
/home/echo/a_project/mots_tools/output_mots/
/home/echo/a_project/mots_tools/mots_eval/test_MOTSchallenge.seqmap

And my test seqmap is like following:

> 0002 empty 000001 000600
0005 empty 000001 000837
0009 empty 000001 000525
0011 empty 000001 000900


And it get this error:
![mots14](https://user-images.githubusercontent.com/25685837/66562899-30051180-eb8f-11e9-8a2e-fa3424b5109f.png)

It makes no sense cause I have data in the directory.

Do you know what happens here ? @pvoigtlaender

**Comment by ahnonay** [comment]
The test seqmap contains sequences 0002, 0005, ... but the screenshot shows that it is trying to load 0001, 0003. Are you sure you are passing the correct seqmap?
Also maybe try renaming the MOT17-01-DPM.txt to 0001.txt

**Comment by EchoAmor** [comment]
![mots15](https://user-images.githubusercontent.com/25685837/66794351-cc366c00-ef33-11e9-8151-91be0c5fb2c8.png)
yeah this is my test.txt, I write it like val.txt. @ahnonay 
I try to rename 2 files to 0001.txt and 0003.txt,  like this ,but get same error
![MOTS16](https://user-images.githubusercontent.com/25685837/66794921-9abea000-ef35-11e9-830a-d1e8b91aa340.png)

**Comment by ahnonay** [comment]
Can you give us exactly the command you use to run mots_tools? Maybe something is wrong there

**Comment by EchoAmor** [comment]
This is my command:

> /home/echo/a_project/TrackR-CNN/forwarded/conv3d_sep2/tracking_data/
/home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/MOT17-01-DPM/
/home/echo/a_project/mots_tools/output_mots/
/home/echo/a_project/mots_tools/mots_eval/test_MOTSchallenge.seqmap

I have to change the tracking  data  name  to  0001.txt ,  the code  can  run .But I DON'T know  how to test all images?  Need I change all txt  to kitti format?

![image](https://user-images.githubusercontent.com/25685837/67172511-33e62e80-f3ee-11e9-9c56-1bc791ba4009.png)
![image](https://user-images.githubusercontent.com/25685837/67172513-3779b580-f3ee-11e9-93a7-91b51ca7db38.png)


But  if  I run the **TrackR-CNN**  to visualize detections ,  it still  get  errors. Can you release  the examples  how you do the work on MOTChanllenge datasets?

This is my TrackR-CNN command :

> configs/conv3d_sep2
{\"task\":\"forward_tracking\",\"dataset\":\"MOTS_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":true,\"visualize_detections\":true,\"MOTS_segtrack_data_dir\":\"/home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/train/\",\"video_tags_to_load\":[\"MOT17-02-DPM\"]}

AND  the error is this 

![mots22](https://user-images.githubusercontent.com/25685837/67172645-b242d080-f3ee-11e9-95e7-454e6d5257fe.png)

I have already changed the input size in **_con3d_sep2.py_** :

![mots21](https://user-images.githubusercontent.com/25685837/67172735-18c7ee80-f3ef-11e9-8c01-33a561d8fe68.png)

**Comment by ahnonay** [comment]
So if I understand correctly you are passing 

> /home/echo/a_project/TrackR-CNN/forwarded/conv3d_sep2/tracking_data/
> /home/echo/a_project/TrackR-CNN/kitti_mots/mot/mot17/test/MOT17-01-DPM/
> /home/echo/a_project/mots_tools/output_mots/
> /home/echo/a_project/mots_tools/mots_eval/test_MOTSchallenge.seqmap

to "python mots_eval/visualize_mots.py"? That seems fine. You just have to make sure the file names in tracking_data and the entries in the seqmap correspond. So yeah, maybe rename them to 0001, 0003, ...
I'm not sure where the error in TrackR-CNN is coming from. You can simply set visualize_detections":false and then do the visualization afterwards using mots_tools.

**Comment by EchoAmor** [comment]
Thanks  !
The file I run is **_TrackR-CNN/main.py_**.
I just want to visualize the detections separately , to check if the objects are detected. MOTs_tools seems to just visualize the tracking results.  I noticed that in the video some people can be detected in the first time , then it will diappear , so I need to check whether the problem is in detection procedure or in tracking procedure. @ahnonay

**Comment by ahnonay** [comment]
Ah, I see. You could also write a small script that takes a detection file as input and outputs a "fake" tracking file (basically, you just have to remove the ReID vectors and add some random tracking id to each detection). I'm sorry that code for this does not exist yet.

**Comment by EchoAmor** [comment]
It's ok，Thanks for replying

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
