### ISSUE TITLE
Hello! May I ask a question about multi-target detection results?

### ISSUE THREAD

**Issue by yinhai86924** [VisualComputingInstitute/TrackR-CNN#38]
I opened one of the txt documents with detection results, but I do not understand what the numbers meant.  as trackrcnn_detections result:   When I opened the result file, there was a mess of code.
![QQ截图20191008225710](https://user-images.githubusercontent.com/45553479/66407124-3ffde380-ea1f-11e9-94cf-8d10b04928a6.png)

**Comment by pvoigtlaender** [comment]
Please have a look at https://www.vision.rwth-aachen.de/page/mots under Annotation Format -> txt format

**Comment by yinhai86924** [comment]
> Please have a look at https://www.vision.rwth-aachen.de/page/mots under Annotation Format -> txt format

Thank you ! I see it, but, I want to know  what is mean of rle?

**Comment by pvoigtlaender** [comment]
You can decode it into a mask using pycocotools, e.g. 

```
import pycocotools.mask as cocomask
rle = {"size": [375, 1242], "counts": "WSV:2d;1O10000O10000O1O100O100O1O100O1000000000000000O100O102N5K00O1O1N2O110OO2O001O1NTga3"}
mask = cocomask.decode(rle) # mask is now a numpy array
print(mask.shape)
```

**Comment by ahnonay** [comment]
The file you opened shows detection results not tracking results (in other words: these results have not yet been merged into tracks). The format is

time frame 
bounding box (four numbers)
detection score
class id
image height
image width 
rle mask
association vector

**Comment by yinhai86924** [comment]
> You can decode it into a mask using pycocotools, e.g.
> 
> ```
> import pycocotools.mask as cocomask
> rle = {"size": [375, 1242], "counts": "WSV:2d;1O10000O10000O1O100O100O1O100O1000000000000000O100O102N5K00O1O1N2O110OO2O001O1NTga3"}
> mask = cocomask.decode(rle) # mask is now a numpy array
> print(mask.shape)
> ```

Thank you for your help!

**Comment by yinhai86924** [comment]
> The file you opened shows detection results not tracking results (in other words: these results have not yet been merged into tracks). The format is
> 
> time frame
> bounding box (four numbers)
> detection score
> class id
> image height
> image width
> rle mask
> association vector

About this paper , Object detection baed on Instance segementation algorithm, the result of detection have bounding box with four parameters  (x, y w, h )?

**Comment by pvoigtlaender** [comment]
The first two numbers of the four parameters are the top left corner (x0,y0). The two numbers afterwards are the bottom right (x1, y1) coordinates (could also be width and height, but I think it's the corner).

**Comment by yinhai86924** [comment]
> The first two numbers of the four parameters are the top left corner (x0,y0). The two numbers afterwards are the bottom right (x1, y1) coordinates (could also be width and height, but I think it's the corner).

Thank you , but, I  have a question, I want to konw whether the bounding box is detection result of the Track RCNN ? It adopts instance segementation method, I think there are many points of outputs

**Comment by pvoigtlaender** [comment]
Yeah, it's the raw detection results including segmentation masks of TrackR-CNN (the mask is encoded as rle)

**Comment by yinhai86924** [comment]
> Yeah, it's the raw detection results including segmentation masks of TrackR-CNN (the mask is encoded as rle)

Thank you for your help!  where is the output of bounding box in code?

**Comment by pvoigtlaender** [comment]
Please have a look at
https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder.py#L147
and at
https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder.py#L207
and at
https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder_util.py#L63

**Comment by yinhai86924** [comment]
> Please have a look at
> https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder.py#L147
> 
> 
> and at
> https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder.py#L207
> 
> 
> and at
> https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder_util.py#L63

I found it，I really appreciate your warm help！

**Comment by yinhai86924** [comment]
> The file you opened shows detection results not tracking results (in other words: these results have not yet been merged into tracks). The format is
> 
> time frame
> bounding box (four numbers)
> detection score
> class id
> image height
> image width
> rle mask
> association vector

what is time frame?  0 1109.5554 179.36575 1197.3547 314.45007 0.9999083 2 375 1242 ......
0 772.6455 172.86652 869.1234 353.39307 0.9718455 2 375 1242 ......
0 227.92526 192.79128 240.0155 219.55272 0.7975448 2 375 1242 ........  
0 76.26672 192.66322 137.3797 214.80476 0.5851311 1 375 1242 ...........
from above. I want to know  whether 0 it represents the first frame , but in the first frame, it detects many objects? so,there are many bounding boxs and masks in the first frame. Can I understand that?

**Comment by pvoigtlaender** [comment]
Yes, it's frame 0 and in this frame there are many detections.

**Comment by yinhai86924** [comment]
> Yes, it's frame 0 and in this frame there are many detections.
Thank you !  I have a question about how to interpret the Tracking results format as follows :
0 1 1 375 1242 T6W1`:0000000O100O1OO11O1000O01O1O100O100000000O101O002N0O10000N2000000000000000N2O10000O10000O100O100O10000000000000000000000000000O1000000000000000000O100000000O11O000011N001O00010O00100O10O0001N2N4L3L3N2N10000000Yjo<
0 2 1 375 1242 Pb^2?X;0O1O2M2O2N001O10O01O1O1O100O1O100O100O1000000O101O00000N201O1O000000O1O100O100O10000O10000001O0002N1O0O2O00dTT;
0 3 1 375 1242 edV11e;f0ZO3N1N1O4L100O100OO11O10O0100O100O1N2N10100O10000O100O100O1000001O00000000000O101O002N0000000O10000N200000N2O10000O100O1O100O10000O10000000000000000000000000000000000000000000000O1001O00001O0000001OO100O3N1N2N2O0O100_OmE^OS:b0mE^OS:a0nE_OW`g;

**Comment by yinhai86924** [comment]
> The file you opened shows detection results not tracking results (in other words: these results have not yet been merged into tracks). The format is
> 
> time frame
> bounding box (four numbers)
> detection score
> class id
> image height
> image width
> rle mask
> association vector

I have a question about how to interpret the Tracking results format as follows :
0 1 1 375 1242 T6W1:0000000O100O1OO11O1000O01O1O100O100000000O101O002N0O10000N2000000000000000N2O10000O10000O100O100O10000000000000000000000000000O1000000000000000000O100000000O11O000011N001O00010O00100O10O0001N2N4L3L3N2N10000000Yjo<
 0 2 1 375 1242
Pb^2X;0O1O2M2O2N001O10O01O1O1O100O1O100O100O1000000O101O00000N201O1O000000O1O100O100O10000O10000001O0002N1O0O2O00dTT; 
0 3 1 375 1242 edV11e;f0ZO3N1N1O4L100O100OO11O10O0100O100O1N2N10100O10000O100O100O1000001O00000000000O101O002N0000000O10000N200000N2O10000O100O1O100O10000O10000000000000000000000000000000000000000000000O1001O00001O0000001OO100O3N1N2N2O0O100_OmE^OS:b0mE^OS:a0nE_OWg;

**Comment by pvoigtlaender** [comment]
the format is
time_frame id class_id img_height img_width rle

so for example
0 2 1 375 1242
Pb^2X;0O1O2M2O2N001O10O01O1O1O100O1O100O100O1000000O101O00000N201O1O000000O1O100O100O10000O10000001O0002N1O0O2O00dTT;

means

time frame 0
track_id 2
class_id 1 (should be car)
height of image 375
width of image 1242
rle Pb^2X;0O1O2M2O2N001O10O01O1O1O100O1O100O100O1000000O101O00000N201O1O000000O1O100O100O10000O10000001O0002N1O0O2O00dTT;

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
