### ISSUE TITLE
MOTS test image display problems

### ISSUE THREAD

**Issue by chunniunai220ml** [VisualComputingInstitute/TrackR-CNN#39]
Hi ! Thanks for your sharing. I have tested MOTS dataset sucessfully, but the image can not show the mask correctly, the vis/track image as follow:
![11](https://user-images.githubusercontent.com/17668109/67083707-39652e00-f1ce-11e9-88c0-80e4c22b9fbe.PNG)

I think the problem is caused by the test image size,and I have changede the configs/conv3d_sep2 as :
"input_size_val":[1080,1920]

but no works. 
so  what should I do to get track images with correct masks?

**Comment by trungmanhhuynh** [comment]
@chunniunai220ml, 
In the file configs/conv3d_sep2, make sure you have "input_size_val": [1080, 1920] instead of   "input_size_val": [375, 1242]". This worked for me. You can also do it by overwritting the input arguments.
