### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by josheligoldman** [VisualComputingInstitute/TrackR-CNN#40]
When I run the command:

python main.py configs/conv3d_sep2

I get the following error:

Traceback (most recent call last):
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/main.py", line 32, in <module>
    tf.compat.v1.app.run(main)
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/venv/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/main.py", line 27, in main
    engine = Engine(config)
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/core/Engine.py", line 41, in __init__
    name="trainnet")
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/network/Network.py", line 16, in __init__
    self.input_tensors_dict = dataset.create_input_tensors_dict(self.batch_size)
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/datasets/Dataset.py", line 278, in create_input_tensors_dict
    self._load_inputfile_lists()
  File "/Users/joshgoldman/PycharmProjects/MultiObjectTrackingAndSegmentation/datasets/Dataset.py", line 260, in _load_inputfile_lists
    assert len(l) > 0
AssertionError

**Comment by pvoigtlaender** [comment]
It's some problem with the paths, the data is not found. Please try to set the paths explicitly or you can do some debugging into load_inputfile_lists and see which path it tries to load

**Comment by EchoAmor** [comment]
Hello ，I have met the same problem when I use the command to train on MOTS dataset.

> python main.py configs/conv3d_sep2

The error is like this 

![Screenshot from 2019-11-11 14-24-26](https://user-images.githubusercontent.com/25685837/68565597-fe81ad80-048e-11ea-94ed-df055a4e44b4.png)

After I debug,I found the problem is in the **_Dataset.py_**, can u tell me how the **_read_inputfile_lists()_**  work  in the class **_FileListDataset()_**, I can't find where it is .
![Screenshot from 2019-11-11 14-27-34](https://user-images.githubusercontent.com/25685837/68565764-6e903380-048f-11ea-8c92-54294962d0f5.png)

Thanks very much!!! @pvoigtlaender @josheligoldman

**Comment by ahnonay** [comment]
read_inputfile_lists is implemented in the subclasses of FileListDataset
To train on MOTS Challenge, use the MotsChallengeDataset and make sure all the paths are working right. For example, you could use a debugger to step through read_inputfile_lists in MotsChallengeDataset and see where self.data_dir points to and whether it finds any files

**Comment by EchoAmor** [comment]
Thanks！ I'll try!

**Comment by EchoAmor** [comment]
Sorry，I have a question, u said we couldn't train on MOTS chanllenge in another question  right? But here you say we can , I got a little confused  @ahnonay

**Comment by pvoigtlaender** [comment]
> Sorry，I have a question, u said we couldn't train on MOTS chanllenge in another question right? But here you say we can , I got a little confused @ahnonay

It is possible to train on MOTS Challenge. To what comment do you refer specifically?

**Comment by EchoAmor** [comment]
this one #42 @pvoigtlaender

**Comment by ahnonay** [comment]
Apologies for the confusion. It is of course possible to train on sequences 2, 5, 9 and 11 of MOT. These four sequnces are part of MOTSChallenge, so we have segmentation annotations for them. It is not possible to train on the rest of the sequences of MOT, because there, only bounding box annotations exist (this is what I meant in the other comment).

**Comment by EchoAmor** [comment]
Got it,but If only trained on these four sequences, will the generalization ability of this network be weak?Do u have any idea to solve this problem please? Thanks a lot for replying. @ahnonay

**Comment by ahnonay** [comment]
As an estimate for the generalization ability when training on MOTS Challenge you can look at Table 5 of the paper. Our results there were obtained with cross-validation and thus should roughly give an idea how good performance will be on the other sequences of MOT Challenge.
Generalization to out-of-domain data (i.e. other videos than MOT Challenge) will probably not be great, since the dataset is rather small, as you noted.

**Comment by pvoigtlaender** [comment]
Seems the issue has been resolved. Feel free to re-open if necessary.

**Comment by SamihaSara** [comment]
@EchoAmor I am having the same error while trining on KITTI_MOTS. Did you solve this issue? Could you please share the steps?


> Hello ，I have met the same problem when I use the command to train on MOTS dataset.
> 
> > python main.py configs/conv3d_sep2
> 
> The error is like this
> 
> ![Screenshot from 2019-11-11 14-24-26](https://user-images.githubusercontent.com/25685837/68565597-fe81ad80-048e-11ea-94ed-df055a4e44b4.png)
> 
> After I debug,I found the problem is in the **_Dataset.py_**, can u tell me how the **_read_inputfile_lists()_** work in the class **_FileListDataset()_**, I can't find where it is .
> ![Screenshot from 2019-11-11 14-27-34](https://user-images.githubusercontent.com/25685837/68565764-6e903380-048f-11ea-8c92-54294962d0f5.png)
> 
> Thanks very much!!! @pvoigtlaender @josheligoldman

**Comment by EchoAmor** [comment]
@SamihaSara I run this half a year ago, can't remember so clearly, just know it's the problem with your path, u can see
#42 ,make sure your file is like 0000,0001....And make sure the path in **_configs/conv3d_sep2_** is your absolute path

**Comment by SamihaSara** [comment]
@EchoAmor  Thanks for helping. I checked #42  and file format, tested with absolute path also. But could not solve. Now, Can you remember, when you trained this model, did you need all 3 datasets(MOTS, KITTI_MOTS, Mapillary)?

**Comment by EchoAmor** [comment]
> @EchoAmor Thanks for helping. I checked #42 and file format, tested with absolute path also. But could not solve. Now, Can you remember, when you trained this model, did you need all 3 datasets(MOTS, KITTI_MOTS, Mapillary)?

no,no need for 3 datasets. I still think  it's your path problem ,check it more seriously

**Comment by SamihaSara** [comment]
@EchoAmor  Do you mean I have put datasets path wrong? Should I put paths like this--  ~/TrackRCNN/data/KITTI_MOTS/train/images/ ?

**Comment by EchoAmor** [comment]
emmm,I don't remember,you need to check by yourself. I wasted a lot of time on this too at that time, you need to check very carefully ,  try to check your path with the error hint , may know where the problem lies,good  luck

> @EchoAmor Do you mean I have put datasets path wrong? Should I put paths like this-- ~/TrackRCNN/data/KITTI_MOTS/train/images/ ?

**Comment by SamihaSara** [comment]
@EchoAmor yes,  just went through other related issues. Now will try again.  Thanks for the prompt reply.
