### ISSUE TITLE
Meet some problem when training on MOT dataset

### ISSUE THREAD

**Issue by EchoAmor** [VisualComputingInstitute/TrackR-CNN#42]
I want to train on MOT dataset , but I found the instance.txt only have 0002,0005,0009,0011

![motrain1](https://user-images.githubusercontent.com/25685837/67732153-6d91e780-fa35-11e9-9671-90331f4d52a7.png)

But the train directory has following  images, Need I change their directory   name to 0002,0005,0009,0011? 

![motrain2](https://user-images.githubusercontent.com/25685837/67732288-cbbeca80-fa35-11e9-8f03-563b726437a4.png)

How to deal with other directories please? Thanks !

**Comment by EchoAmor** [comment]
I use the command to train

> /home/echo/anaconda3/envs/MOTS/bin/python /home/echo/a_project/TrackR-CNN/main.py configs/conv3d_sep2

get this error

![bug12](https://user-images.githubusercontent.com/25685837/67749257-bebacf00-fa67-11e9-80af-7fabf9fb086a.png)
 
can u tell me how to solve this problem ?

**Comment by pvoigtlaender** [comment]
Hi,

please try replacing 
"dataset": "MOTS_segtrack",
with
"dataset": "MOTS_challenge",

**Comment by ahnonay** [comment]
You can take either one of the DPM/FRCNN/SDP folders. So for example, rename
MOT17-02-DPM -> 0002
MOT17-05-DPM -> 0005
MOT17-09-DPM -> 0009
MOT17-11-DPM -> 0011
and delete the rest. Also note that currently, we only have sequences 2,5,9 and 11 annotated.

**Comment by EchoAmor** [comment]
Thanks! I will try  @pvoigtlaender @ahnonay 
BTW, If I need to train the code on MOT dataset, I can only use 2,5,9,11 the 4 directories too? How about other data?

**Comment by ahnonay** [comment]
So far, instance segmentations only exist for these four sequences. The MOT datasets only provide bounding box annotations, so you cant train TrackR-CNN on that

**Comment by EchoAmor** [comment]
oh I see . I am still working on that. Thanks for replying , Once I get results I will upload here.

**Comment by ahnonay** [comment]
Closing for now, please reopen if needed
