### ISSUE TITLE
There are some places that don't understand about the reid parameters.

### ISSUE THREAD

**Issue by lalalabiubiu** [VisualComputingInstitute/TrackR-CNN#46]
Thanks for sharing, I tried to train my own dataset with TrackRCNN, and the tracking effect is not very good. I doubt that the reid_euclidean_offset_car series parameter needs to be fine-tuned. But I don't understand how the values of these parameters are determined. I hope your guidance.Thank you! @pvoigtlaender 
`"association_threshold_car": 0.8165986526897969, "keep_alive_car": 4, "reid_euclidean_offset_car": 8.810218833503743, "reid_euclidean_scale_car": 1.0090931467228708,`

**Comment by ahnonay** [comment]
Hey! These parameters are determined via random tuning on our training set. You can also run the tuning yourself with the segtrack_tune_experiment.py script. See the "Tuning" section in the Readme.

**Comment by lalalabiubiu** [comment]
Thanks for your reply, I ran the tuning code and got these parameters. But my sMOTSA is negative. Is there something missing?@pvoigtlaender

**Comment by ahnonay** [comment]
Negative sMOTSA can happen e.g. if the model makes a lot of false positive errors. Maybe the detection_confidence_threshold parameters should be higher. You can try playing with the parameters a bit by hand. 
The tuning script also sets some reasonable ranges that the parameters should be in. It is possible that these ranges must be adjusted for other data.

**Comment by lalalabiubiu** [comment]
Thank you very much！I will try it！

**Comment by ahnonay** [comment]
Closing for now, please reopen if needed
