### ISSUE TITLE
trianing with pre-model meet a problem.(checkpoint file couldn't find)

### ISSUE THREAD

**Issue by Michaelphm** [VisualComputingInstitute/TrackR-CNN#47]
thank you share the excellent work with us,  I have meeted a problem when running the code with pretrained model.  I have changed the "load_init" point  to the path to the pretrained model, and I sure it no problem with the path. but it still throw an error that 
" Couldn't find 'checkpoint' file or checkpoints in given directory /home/phm/TrackR-CNN/models".
![image](https://user-images.githubusercontent.com/20236727/69785034-30ff0a80-11f2-11ea-8d60-8eebb961a9d3.png)

The trackrcnn_init.zip only contained three files, "XX.meta", "XX.index" and "XX.data-00XXX".
![image](https://user-images.githubusercontent.com/20236727/69785118-52f88d00-11f2-11ea-9d65-94859a6d8256.png)
 I don't know if this file is missing, or other problem caused the error.  follow is the picture of error  description.
![image](https://user-images.githubusercontent.com/20236727/69785392-ea5de000-11f2-11ea-972c-ead8a361e805.png)
 list_variables(filename)  called a function load_checkpoint(checkpoint_dir), and the later can't find checkpoint file.

**Comment by ahnonay** [comment]
Can you try putting the three files in a folder "conv3d_sep2" inside "models/"?

**Comment by Michaelphm** [comment]
> Can you try putting the three files in a folder "conv3d_sep2" inside "models/"?

Thank you for your reply, it will work after add a folder "conv3d_sep2" inside "models/".

**Comment by SamihaSara** [comment]
@Michaelphm Was your problem solved after putting these 3 files under conv3d_sep2? I have also followed this solution but still getting this error.
