### ISSUE TITLE
How to train my dataset with TrackRCNN?

### ISSUE THREAD

**Issue by lalalabiubiu** [VisualComputingInstitute/TrackR-CNN#5]
Thanks for sharing, I downloaded your data set and tested it, but I don't quite understand how your data set is made. Is it feasible to convert to txt format with labelme or labelimg? How to train my own data set? @pvoigtlaender

**Comment by pvoigtlaender** [comment]
We have both the txt format and the png format versions which are equivalent (they are described in more detail at https://www.vision.rwth-aachen.de/page/mots).
The mots_tools repository provides a script to convert from png to txt format: https://github.com/VisualComputingInstitute/mots_tools/blob/master/mots_common/images_to_txt.py
It basically just uses the rle encoding provided by coco.
If you want to use your own dataset you have to find a way to export it in either png or txt format.
I didn't hear about labelimg, but we also used labelme in our annotation pipeline. You can read the json format of labelme in with python and then export as png (a few lines of code will be needed for that).

**Comment by lalalabiubiu** [comment]
Thank you very much for your reply. I want to label my own data in the format of the MOT dataset with labelme, but I see that your dataset contains ReID. How is this ReID   determined?
@pvoigtlaender

**Comment by pvoigtlaender** [comment]
I'm not sure what you mean with ReID here, in the dataset we label the instances with a consistent ID over time, is that what you mean?
If yes, then just make sure that somewhere (for example the filename of the jsons you write out with labelme) you keep the instance ID and put it in when exporting to the png/txt format.
Be aware that labeling each frame with labelme without the semi-automatic annotation procedure we used will be quite tedious

**Comment by lalalabiubiu** [comment]
Sorry, I see rle as a reid. I mean how to define this rle? Also, is the semi-automatic annotation tool mentioned in your paper open source? Thank you very much. @pvoigtlaender

**Comment by pvoigtlaender** [comment]
rle just means run length encoding, an efficient encoding of the mask of an object used by COCO. Using the coco tools you can easily convert numpy masks to rles.

The semi-automatic procedure is not just a single tool, the details are explained in the paper. The polygons were drawn using labelme, the rest is not really published at the moment, but we plan to do that (not sure yet when).

**Comment by lalalabiubiu** [comment]
Thank you very much for your answers, I will try to do a small part of the dataset and train it。
