### ISSUE TITLE
CPU utilisation

### ISSUE THREAD

**Issue by GuiLech** [VisualComputingInstitute/TrackR-CNN#51]
While forwarding a video, I've noticed that my cpu utilization has some peak up to 100% on one core.
This peak correspond to a hole in the gpu utilization.
I've conclude that the image segmentation is made with the gpu and after, the tracking is made with the cpu? Is that correct?

I've test the code on a computer with a GTX 1070 and a P6000 and obtained similar performance.

Is there a way to only use the gpu?

**Comment by pvoigtlaender** [comment]
Hi,

it's correct, the network is evaluated on the GPU, the tracking is done on CPU. You could try to optimize that but moving the tracking code to the GPU or by just speeding up the tracking process on the CPU, but this will be some effort.

**Comment by GuiLech** [comment]
Thanks for the respond,
I will look at this

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
