### ISSUE TITLE
GPU memory leak when forwarding

### ISSUE THREAD

**Issue by mikexyl** [VisualComputingInstitute/TrackR-CNN#52]
Hello guys,
My device is gtx 970 4G. Traning works fine on my machine when reducing the batch size to 2. But when I try to do forwarding on MOTSchallenge datasets, it always reported resource exhausted, even with batch size reduced to 1. the error reported is:
`Limit:                  3397451776
InUse:                   262596352
MaxInUse:               1055064064
NumAllocs:                   15181
MaxAllocSize:            717225984

2020-02-11 23:14:33.566204: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ***************_____________________________________________________________________________________
2020-02-11 23:14:33.566221: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at crop_and_resize_op.cc:173 : Resource exhausted: OOM when allocating tensor with shape[881,28,28,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
`
i think its because gpu memory exhausted, right? But I already reduced batch size to 1, what else should i do to fix this?

And another question, How to decode the trackcnn_detection files downloaded from MOTSchallenge website? I tried to run it with the tracking command showed in the intro, but it doesnt recognise the detection file. I want to import and decode the detections so i can do some process my own, which part of code i should refer?

I am still a new guy in tracking and gpu computing. Thank you guys so much for any help!

**Comment by pvoigtlaender** [comment]
For the forwarding, we did not optimize it for memory usage. The software is not really designed for a 4GB memory card. 
One possibility is to reduce the input size, but this would probably make the results worse.

**Comment by mikexyl** [comment]
yeah,, I guessed so. And I just figured out the detection file problem. Thanks.
