### ISSUE TITLE
Training on my own data

### ISSUE THREAD

**Issue by johnperuzzi** [VisualComputingInstitute/TrackR-CNN#53]
Reading the readme, I am a little confused about the steps needed to train the model on my own dataset - hoping to fit the model slightly better to my task. 

There seems to be a lot of complexity within the codebase about registering datasets. Is there a simple way to accomplish this?

**Comment by pvoigtlaender** [comment]
An easier way might be to have your dataset "look like" KITTI (i.e. make it the same format) and then change "KITTI_segtrack_data_dir" in the config to point to your own data.

**Comment by johnperuzzi** [comment]
thank you - now after having done this I'm still a little confused about the role of training.txt and validation.txt and I'm having trouble figuring it out through the code? Should I remake these files?

**Comment by johnperuzzi** [comment]
For context, I'm running 
python main.py configs/conv3d_sep2

And my file structure now looks like
data/
  SIM_DATA/
    train/
      images/
      instances/

now pointing at /data/SIM_DATA/train/    in the config files, but I'm getting this error when I train:

Not found: /data/SIM_DATA/train/images/0002/frame000147.png; No such file or directory

But then the model evens of trains a little anyway before crashing

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed

**Comment by jong372** [comment]
@johnperuzzi where you able to annotate your own dataset, resulting in the required .png format for TrackR-CNN?
