### ISSUE TITLE
how to pretune the networks on coco and Mapillary dataset? Could you provide the codes?

### ISSUE THREAD

**Issue by LiangHann** [VisualComputingInstitute/TrackR-CNN#54]
how to pretune the networks on coco and Mapillary dataset? Could you provide the codes?

**Comment by pvoigtlaender** [comment]
@ahnonay can you please share the configs for that?

**Comment by ahnonay** [comment]
Unfortunately, I don't have a config for that. We trained our COCO/Mapillary model not with this codebase but with Tensorpack directly. You can probably do the same. We use the same names for our weights, so you should be able to use the Tensorpack model with this codebase with only few adjustments. The Tensorpack code version we used is about one and a half years old, though.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
