### ISSUE TITLE
Running model on webcam

### ISSUE THREAD

**Issue by richard-salaschavez** [VisualComputingInstitute/TrackR-CNN#56]
Is it possible to run the model on a webcam feed? Is there some code for this? After reading the README it doesn't seem straight forward.

**Comment by ahnonay** [comment]
There is no code for that, no. You would need to manually obtain frames from the webcam feed and input them to the network. I would guess however that TrackR-CNN is simply too slow to be useful for live streams.

**Comment by richard-salaschavez** [comment]
Ok. What is the slowest step of TrackR-CNN? Is it having to run the ResNet model three times for t-1, t, and t+1?

**Comment by pvoigtlaender** [comment]
Hi,

yes, I think running the backbone should be the slowest step. Additionally the Mask R-CNN second stage is probably also relatively expensive, but I expect it to be still less than the backbone. If you want to know the details you'll have to run a profiler.

**Comment by ahnonay** [comment]
I agree. Of course, using a smaller ResNet for example will always increase speed and decrease quality. Closing this for now, please reopen if needed.
