### ISSUE TITLE
How to run model as Online Tracking?

### ISSUE THREAD

**Issue by hoangtuanvu** [VisualComputingInstitute/TrackR-CNN#6]

**Comment by pvoigtlaender** [comment]
Hi,

the model can in theory run near-online (the 3D convs look a few frames into the future, so it's not fully online, but you can use the version without 3D convs which performs almost the same to get true online processing). 
However, we did not implement actual online processing. That means that our code processes a whole sequence at a time but still produces a result without using offline information. 
If you want true online processing, you would have to adapt the code.

**Comment by hoangtuanvu** [comment]
@pvoigtlaender Thank you for your answer. I will try to customize.

**Comment by gh18l** [comment]
@pvoigtlaender Can you tell me what is the fps probably if I remove the 3D convs?

**Comment by pvoigtlaender** [comment]
I think the speed should slightly increase but it won't make a too large difference, so expect still around 2fps.

**Comment by richard-salaschavez** [comment]
did you guys try looking feeding t-2, t-1, t instead of t-1, t, t+1? were the results comparable?

**Comment by ahnonay** [comment]
No, we did not test this. It's a good idea to get "true" online processing and should be possible with some small adaptations to the code.
