### ISSUE TITLE
Do you have the codes to transform the format of KITTI MOTS and MOTSChallenge to COCO format or Pascal VOC format? 

### ISSUE THREAD

**Issue by LiangHann** [VisualComputingInstitute/TrackR-CNN#60]
Do you have the codes to transform the format of KITTI MOTS and MOTSChallenge to COCO format or Pascal VOC format? Thanks.

**Comment by ahnonay** [comment]
Yes, however keep in mind this code is more or less "internal", i.e. has not been tested much and is not polished.
[gt_in_coco_format.zip](https://github.com/VisualComputingInstitute/TrackR-CNN/files/4365326/gt_in_coco_format.zip)

**Comment by LiangHann** [comment]
> Yes, however keep in mind this code is more or less "internal", i.e. has not been tested much and is not polished.
> [gt_in_coco_format.zip](https://github.com/VisualComputingInstitute/TrackR-CNN/files/4365326/gt_in_coco_format.zip)

Thanks very much.
