### ISSUE TITLE
The reason why ResNet C2 weights are frozen?

### ISSUE THREAD

**Issue by emjay73** [VisualComputingInstitute/TrackR-CNN#62]

**Comment by ahnonay** [comment]
These very early weights are trained only on ImageNet. We expect them to extract basic features like edges, corners etc so they dont need to be adapted to the task.

**Comment by emjay73** [comment]
I see. Did you also try not to freeze ResNet C2 weight?

**Comment by ahnonay** [comment]
No, we did not try that

**Comment by emjay73** [comment]
I just wondered whether I could get some insights about it. (like.. why C2 layer is the only layer that is frozen amongst ResNet..? Why C2 especially? What about C1?)

**Comment by ahnonay** [comment]
The layers before C2 are also frozen (it is done using a tf.stop_gradient operation). You could probably do the same after C3 and it would not change results by much.

**Comment by emjay73** [comment]
Oh! I must have missed it. Thank you for your explanation. I'll close the issue.
