### ISSUE TITLE
A queation about dictionary “model” in Readme

### ISSUE THREAD

**Issue by Xiangyu33** [VisualComputingInstitute/TrackR-CNN#63]
Hi there, thanks for your code!  But I just have a queestion about "model" dict
in the README, we can see:
models/
- conv3d_sep2/
-- conv3d_sep2-00000005.data-00000-of-00001
-- conv3d_sep2-00000005.index
-- conv3d_sep2-00000005.meta
- converted.data-00000-of-00001
- converted.meta
- converted.index 

but where to download the files in "models"?
thanks your time

**Comment by pvoigtlaender** [comment]
You can find them here:
https://omnomnom.vision.rwth-aachen.de/data/trackrcnn/

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed.
