### ISSUE TITLE
Question about mots_eval

### ISSUE THREAD

**Issue by LiXm1002** [VisualComputingInstitute/TrackR-CNN#64]
Thanks for sharing!
When I use eval.py in mots_tools to eval my reslut, It raise `Objects with overlapping masks`. I find that
 `      elif rletools.area(rletools.merge([combined_mask_per_frame[frame], mask], intersect=True)) > 0.0:
        assert False, "Objects with overlapping masks in frame " + fields[0]`
in eval.py. I am curious why this restriction is required.

**Comment by pvoigtlaender** [comment]
Hi,

it was a design decision of the MOTS task. Intuitively, every pixel can only belong to one object, so we decided not to allow overlapping masks.

**Comment by LiXm1002** [comment]
Thank you for your reply.
In that case, if the mask overlaps, I can’t use this program to evaluate it, right?
so sad. T_T

**Comment by pvoigtlaender** [comment]
You can disable the overlap check, but keep in mind that your result will not be "valid".
You should better do some post-processing to get rid of the overlap.

**Comment by LiXm1002** [comment]
OK，I will try it.

**Comment by ahnonay** [comment]
As a hint, you could use something like the detector confidence to preserve pixels of very confident detections and to drop pixels of not-so-confident detections.

Closing this for now, please reopen if needed.
