### ISSUE TITLE
the annotation of KITTI_MOTS

### ISSUE THREAD

**Issue by chenshi3** [VisualComputingInstitute/TrackR-CNN#65]

**Comment by chenshi3** [comment]
Why the class_id in annotation is 10? 
The class_id should be 1 or 2.

**Comment by chenshi3** [comment]
What is the mean of a object which class_id is 10?

**Comment by chenshi3** [comment]
7 10000 10 375 1242 TXV1R1e:000000000000000000000000000000000000000000000000000···
8 10000 10 375 1242 ]mY1R1e:0000000000000000000000000000000000000000····
9 10000 10 375 1242 Un]1X1_:00000000000000000000000000000000000000000000000000000···
10 10000 10 375 1242 Sl`1V1a:0000000000000000000000000000000000000000000000000000····
the boxes decoded from these annotations which class_id are 10 are strange and wrong obviously

**Comment by chenshi3** [comment]
KITTI MOTS
I see in the dataset page and know the mean of id==10.
However, I visual the box and find that there are some cars and people are ignored and got annotated.

**Comment by pvoigtlaender** [comment]
Hi,

id==10 means it's an ignore region

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed.
