### ISSUE TITLE
Pre-Trained Models download too slow

### ISSUE THREAD

**Issue by zwenc** [VisualComputingInstitute/TrackR-CNN#66]
hello, The download of resources is too slow. Could you upload resources to other online disks.

**Comment by pvoigtlaender** [comment]
Hi,

I created an alternative download link here: https://drive.google.com/file/d/1fGVzwwIdhwxOkNTOCvZ63NSmw5EES6ri

**Comment by ahnonay** [comment]
Closing for now, please reopen if needed
