### ISSUE TITLE
Make  Dataset

### ISSUE THREAD

**Issue by EddieEduardo** [VisualComputingInstitute/TrackR-CNN#67]
Hi，thanks a lot for your TrackR-CNN code sharing.

But I'm still confused about making my own MOTS dataset，could you please share your code about 

dataset making with us ? We'll appreciate it a lot. 

                All the best.

**Comment by pvoigtlaender** [comment]
Hi,

first to clarify: with dataset making you mean the semi-automatic annotation procedure, or is it more about the file formats?

**Comment by EddieEduardo** [comment]
Hello，thanks for repyling , I meant the semi-automatic annotation procedure, thanks very much for sharing.

**Comment by pvoigtlaender** [comment]
Hi,

unfortunately we're currently quite busy with other things (mainly preparing the MOTS workshop). We can still release code for the annotation procedure, but it will take some time till we get to that (it will require some refactoring and adding explanations from our side).
The key to the annotation procedure is Box2Seg/Refinement-net, you can find a (slightly modified version) of the code here: https://github.com/JonathonLuiten/PReMVOS/tree/master/code/refinement_net

**Comment by EddieEduardo** [comment]
Hi, thanks for your replying, but I still have a question on overlapping, which is ,

**1.** What if a region proposal simultaneously contains a whole object **A** and a small part of another object **B** (A and B don't overlap)? Does this mean this small part which belongs to **B** will be mistakenly labeled to **A** ? 

**2.** What if **A** and **B** overlap ? Does the overlapped part will only be labeled to a single one ID (**A** **_or_** **B**) instead of 2 ID (**A** **_and_** **B**) ?

Thanks very much for replying.

**Comment by ahnonay** [comment]
Hi,

does your question refer to the semi-automatic annotation procedure or to TrackR-CNN?

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed

**Comment by jong372** [comment]
@EddieEduardo where you able to do the annotation of images yourself. Hence, getting the required .png format?
