### ISSUE TITLE
Questions on successor_frame_filename_np

### ISSUE THREAD

**Issue by EddieEduardo** [VisualComputingInstitute/TrackR-CNN#68]
Hi, thanks for sharing the codes, but there are two places I'm confused about, could you please 
make an explanation?

The last function in **datasets/KITTI/segtrack/KITTI_segtrack.py**

"""
def successor_frame_filename_np(**_filename_**, offset):
     filename = **_filename_**.decode("utf-8")
     sp = filename.split("/")
     png = ".png" in sp[-1]
     t = int(sp[-1].replace(".png", "").replace(".jpg", ""))
     if png:
         filename = "/".join(sp[:-1]) + "/%06d" % **_(t + offset)_** + ".png"
     else:
         filename = "/".join(sp[:-1]) + "/%06d" % (t + offset) + ".jpg"
     return filename.encode("utf-8")
"""
The first place I'm confused about is the parameter **_filename_**, I'm always thinking **_filename_** has the strcture like this **[first image's location, first image's location, ...... , batch size image's location]**, but it appears to have only one image location.

The second place I'm confused about is the variable **_offset_**, why does it have to add **_offset_** to **_t_**, because when running the code, it'll always raise an error showing "Can't Find The File" just because the filename after adding the **_offset_** is overflowed.

Thanks very much for your explanation.

**Comment by ahnonay** [comment]
Hey! Yes, **filename** only contains a single filename. With this function, you can find the **offset**th successor to that file. Of course, if you choose offset too high, that successor might not exist. This needs to be kept in mind when calling this function.
