### ISSUE TITLE
Test TCNN with other instance segmentation results

### ISSUE THREAD

**Issue by detectRecog** [VisualComputingInstitute/TrackR-CNN#69]
Hello,

Is there a way to test the tracking performance of TRCNN based on the segmentation results of other models (eg. Cascade-RCNN)?
Or is there any plan to release the PyTorch code?

**Comment by pvoigtlaender** [comment]
Hi,

we currently don't have plans for a PyTorch version.
If you want to use a cascade R-CNN you would have to modify the code yourself. Note that the detection code is borrowed from tensorpack, which also has code for cascade R-CNN, so it would be possible to adapt the tensorpack cascade R-CNN code here, but it still is some effort.

**Comment by ahnonay** [comment]
Closing for now, please reopen if needed
