### ISSUE TITLE
How to set the file path

### ISSUE THREAD

**Issue by ghost** [VisualComputingInstitute/TrackR-CNN#7]
I am trying to use the KITTI_Segtrack dataset for training.
My current dataset path is "~/data/KITTI_MOTS/train/image_02"
Where should I put the annotation files ( "instance", "instance_txt" and "trackrcnn_detections" )?

**Comment by pvoigtlaender** [comment]
you should have the folders

KITTI_MOTS/train/images/
KITTI_MOTS/train/instances/
KITTI_MOTS/train/instances_txt/
(only 1 of the former 2 are needed, I recommend the txt format)

The path in the config should point to KITTI_MOTS/train/
The detections are only needed if you want to directly load them to perform tracking without using the network. In this case, you have to specify the path explicitly in the config.

**Comment by ahnonay** [comment]
Closing this, please reopen in case of more questions
