### ISSUE TITLE
Training / Performance on YouTube-VIS

### ISSUE THREAD

**Issue by anirudh-chakravarthy** [VisualComputingInstitute/TrackR-CNN#70]
Hi,

I was wondering whether you have tested the network on the YT-VIS dataset. If so, could you provide the performance measures?

If not, what would be possible steps to evaluate on that dataset? While I understand the obvious changes (such as converting the dataset into MOTS format, changing the directory paths), my main concern was regarding tracking. In TrackR-CNN, there are two classes with separate tracking for each class (and therefore, separate parameters - such as association threshold, keep alive etc). While now the number of classes are a lot higher (40), is there any refined way to perform this rather than tuning 40 additional different parameters first and then tracking based on these. In addition, are there any complexities introduced by changing the image resolution for training?

I would appreciate if you could provide me with a direction on how I should go about this? For clarity, if you could provide all the steps I should go through, that would be highly appreciated!

**Comment by pvoigtlaender** [comment]
Hi,

we did not try YT-VIS ourselves, but in this arxiv paper, they did (bad results though): https://arxiv.org/pdf/2003.08429.pdf

**Comment by anirudh-chakravarthy** [comment]
Hi,

Thank you so much for your prompt response. I had actually taken inspiration from the mentioned paper, and wished to train on YT-VIS to verify those results once. 

In this regard, could you help me out by addressing the queries I put forth earlier on how I could proceed?

**Comment by anirudh-chakravarthy** [comment]
Solved over our email discussion :)

Thank you for your prompt responses!
