### ISSUE TITLE
Bounding box regression

### ISSUE THREAD

**Issue by ravich3373** [VisualComputingInstitute/TrackR-CNN#71]
thank you for making the code available, I am trying to fit the model on a different dataset  and found that the bounding box predictions in FRCNN are not good, does the bounding box regression happen when i run "python main.py configs/conv3d_sep2", if not can you briefly explain how to do it, or give some pointers for the same, thanks in advance.

**Comment by pvoigtlaender** [comment]
Yes, bounding box regression should always be active. Maybe it's hard to learn it on your dataset, since the regression is class-specific and maybe you don't have enough data for some classes

**Comment by ahnonay** [comment]
Closing this, please reopen if needed
