### ISSUE TITLE
TypeError: make_cost_matrix() missing 1 required positional argument: 'inversion_function'

### ISSUE THREAD

**Issue by PareshKamble** [VisualComputingInstitute/TrackR-CNN#74]
Hi @ahnonay,
Thank you for sharing such a great work.
I followed all the steps given in the ReadMe file.
I was able to successfully run the _forwarding_ command.
However, when I ran _tracking_ command, I got the following error.
`TypeError: make_cost_matrix() missing 1 required positional argument: 'inversion_function'`

Do you know how to get rid of this one?
I could not find anything relevant to this error online, so giving you the trouble.

Thanking you in anticipation!

**Comment by pvoigtlaender** [comment]
Hi,

make_cost_matrix comes from munkres. Maybe munkres changed their API in a newer version? Please try with an older version of munkres.

**Comment by PareshKamble** [comment]
Hi @pvoigtlaender 
Thanks.
In fact, I replaced conda installed version of munkres (1.0.7) with pip version 1.1.2 and it worked.
