### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by EddieEduardo** [VisualComputingInstitute/TrackR-CNN#76]
Hi, thanks a lot for sharing the code, but here comes a problem when running **_python main.py configs/conv3d_sep2_**, which 

is  **_Invalid Argument Error_** resulted in **_TrackR-CNN/network/FasterRCNN_utils.py/line 392_**

**_fg_box_logits = tf.gather_nd(fg_box_logits, indices)_**

The error information I received is as follows:

**_InvalidArgumentError：indices[13]=[13, 1] does not index into param shape [16, 1, 4]_**

It seems that 1 is out of range, but when I traced back and changed it into [16,2,4], raised another problem. 

Could you please tell me where I went wrong or how to solve this problem? Thanks very much.

**Comment by ahnonay** [comment]
It is very difficult to tell where the error comes from. Are you able to execute all the steps in the Readme without errors? Did you change something in the code or use some other data?

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
