### ISSUE TITLE
Handling mask overlaps

### ISSUE THREAD

**Issue by anirudh-chakravarthy** [VisualComputingInstitute/TrackR-CNN#77]
Hi!

Hope you're doing well! Once again, thank you for your prompt assistance with all my previous issues! 

I have some good news, I've been able to run TrackR-CNN on YT-VIS! I've performed some visualizations too, and I'm attaching two for reference.

In the MOTS paper, this line was mentioned: "The resulting tracks can contain overlapping masks which we do not allow for the MOTS task (c.f . Section 4). In such a case, pixels belonging to detections with a higher confidence (given by the classification head of our network) take precedence over detections with lower confidence".

I had a few questions regarding this:

1. By the statement, do you mean that on performing inference i.e forwarding and then tracking, overlapping masks could be predicted by the network, and this will be handled/ignored in evaluation (in the mots_tools repo)? As per [Line 57](https://github.com/VisualComputingInstitute/mots_tools/blob/master/mots_common/io.py#L57) in mots_tools, this doesn't seem to be the case. It seems that overlapping masks result in an error. Could you clarify what the line in the paper means?
2. If you notice in the uploaded images, there are clearly overlapping masks of the same class. It seems as if this may be an issue during evaluation, right?
3. If this is an issue, could you point me to the line where non-maximum suppression is performed to handle such overlaps in TrackR-CNN? How is such overlap avoided for KITTI-MOTS?

<img width="922" alt="Screenshot 2020-07-01 at 6 15 17 PM" src="https://user-images.githubusercontent.com/40134508/86245883-c8cd3880-bbc7-11ea-83e9-30bc51fd1c21.png">

<img width="611" alt="Screenshot 2020-07-01 at 6 34 59 PM" src="https://user-images.githubusercontent.com/40134508/86249895-80187e00-bbcd-11ea-9368-46c1789e0003.png">

**Comment by pvoigtlaender** [comment]
Hi,

the overlap will not be resolved in the evaluation step, but already in TrackR-CNN before writing out the results, please have a look at https://github.com/VisualComputingInstitute/TrackR-CNN/blob/493e6440ad4da624def81c3e0391aa1467d8e85b/forwarding/tracking/TrackingForwarder_util.py#L10

**Comment by anirudh-chakravarthy** [comment]
I see! I'll take a look. Thank you!

**Comment by ahnonay** [comment]
Closing this, please reopen if needed
