### ISSUE TITLE
lstm pretrained model

### ISSUE THREAD

**Issue by bat3a** [VisualComputingInstitute/TrackR-CNN#84]
i want to train on the lstm config, but the config needs the tensorpack pretrained_models, i searched for it but coudn't find it! can you please guide me to how can i get it?

**Comment by ahnonay** [comment]
All configs use the same pretrained model: https://omnomnom.vision.rwth-aachen.de/data/trackrcnn/trackrcnn_init.zip

**Comment by bat3a** [comment]
i thought so, thanks.
