### ISSUE TITLE
How to segment each pedestrian into corresponding folder?

### ISSUE THREAD

**Issue by XiaoBingCQY** [VisualComputingInstitute/TrackR-CNN#85]
If I want to segment pedestrians and put the segmentation results of each pedestrian into a folder (seg_data) and visualize them. How can I run in the terminal.

**Comment by ahnonay** [comment]
Hey! You can get the tracking results from the files in tracking_data after following the Readme. The format of these output files is explained on https://www.vision.rwth-aachen.de/page/mots. You can then separate the pedestrians using the object id in these files

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed

**Comment by nirajdere** [comment]
@XiaoBingCQY  were you able to segment pedestrians?
