### ISSUE TITLE
How to generate the result.txt? RLE format

### ISSUE THREAD

**Issue by JunnHan** [VisualComputingInstitute/TrackR-CNN#87]
How to produce the RLE results like this WSV:2d;1O10000O10000O1O100O100O1O100O1000000000000000O100O102N5K00O1O1N2O110OO2O001O1NTga3?
Looking forward to your reply

**Comment by ahnonay** [comment]
You can use cocotools (https://github.com/cocodataset/cocoapi) for this. Also check the mots_tools repository (https://github.com/VisualComputingInstitute/mots_tools), which loads and encodes these strings.
