### ISSUE TITLE
How to evaluate the performance of MOTS on MOTChallange? I got some errors.

### ISSUE THREAD

**Issue by JunnHan** [VisualComputingInstitute/TrackR-CNN#88]
When I test my own MOTS tracker on MOTChallange MOTS, I got some errors like that
Error: Objects with overlapping masks in frame " + fields[0] + "Error: Objects with overlapping masks in frame 15Error: Objects with overlapping masks in frame 15
How to solve this? How to generate the correct results.txt?

**Comment by pvoigtlaender** [comment]
Hi,

as the error message suggests, for MOTS we require that the result masks are disjoint, i.e. each pixel can be occupied by at most one object. You can either address this directly in your method, or do some simple post-processing, e.g. put smaller masks on top of larger ones, or merge using some confidence score coming from your method.
