### ISSUE TITLE
Use of TrackR-CNN for own dataset - annotation format

### ISSUE THREAD

**Issue by jong372** [VisualComputingInstitute/TrackR-CNN#89]
I want to apply the TrackR-CNN for **apple** detection and tracking. Hence, I need to build a dataset from scratch. For annotation you make use of .png and .txt files, but I'm not able to reproduce your annotation procedure (due to your automatic annotation). This leaves me with some questions;

- Can the .png mask be compared with other .png masks (like PASCAL VOC), or does your mask contain extra information?
- Do you use open source annotation tools for the final step of manual annotation (which e.g. exports your required .png format)?
- Are your masks transferable to other domains (e.g can it be converted to xml, json etc.)?

**Comment by ahnonay** [comment]
Please see https://www.vision.rwth-aachen.de/page/mots for information on the png and txt formats. These were created with an in house tool, but you can probably write a simple editor for them yourself, the format is very simple. Same for converters to any other format.

**Comment by jong372** [comment]
I already checked that website to get my answer, but it doesn't provide it. But does your answer imply that the MOTS **.png**  mask annotations do not differ from other **.png** annotation masks? Hence, it is just a binary mask where the value of the shade of grey is the id of the category as described in the dataset description?

**Comment by pvoigtlaender** [comment]
The value is a combination of category and instance id as stated at https://www.vision.rwth-aachen.de/page/mots

"Note that in both formats an id value of 10,000 denotes an ignore region and 0 is background. The class id can be obtained by floor divison of the object id by 1000 (class_id = obj_id // 1000) and the instance id can be obtained by the object id modulo 1000 (instance_id = obj_id % 1000). The object ids are consistent over time."

**Comment by jong372** [comment]
Indeed! But therefore it's not possible at the moment to create another dataset and train it with your TrackR-CNN. Because this format is not provided in any open source tool. Therefore it is of great value to share your in house annotation tool and the method of annotation. This will boost the research on the multiple object tracking and segmentation.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
