### ISSUE TITLE
Meeting a problem when running the code

### ISSUE THREAD

**Issue by 99demaster** [VisualComputingInstitute/TrackR-CNN#9]
I have imported the KOT training data and instances into "/data/KITTI_MOTS/train/" and have changed the "KITTI_segtrack_data_dir" in config.

However, when I run the command " python main.py configs/conv3d_sep2", the error appears as follows:
"""
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    tf.app.run(main)
  File "/home/lemonweed/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 34, in main
    engine = Engine(config)
  File "/home/lemonweed/2019summer/MOTS/TrackR-CNN-master/core/Engine.py", line 41, in __init__
    name="trainnet")
  File "/home/lemonweed/2019summer/MOTS/TrackR-CNN-master/network/Network.py", line 16, in __init__
    self.input_tensors_dict = dataset.create_input_tensors_dict(self.batch_size)
  File "/home/lemonweed/2019summer/MOTS/TrackR-CNN-master/datasets/Dataset.py", line 268, in create_input_tensors_dict
    self._load_inputfile_lists()
  File "/home/lemonweed/2019summer/MOTS/TrackR-CNN-master/datasets/Dataset.py", line 252, in _load_inputfile_lists
    assert len(l) > 0
AssertionError
"""
I try my best to figure out where is wrong but I failed. Even if I import no training data, the same error appears.

The related code in your project is as follows:
It is in the Dataset.py
if self.inputfile_lists is not None:
      return
    self.inputfile_lists = self.read_inputfile_lists()
    assert len(self.inputfile_lists) > 0
    for l in self.inputfile_lists:
      assert len(l) > 0

It seems that l  = 0 and then the error occurred. But I totally cannot solve it.
I really hope that you can help me. Thanks.

**Comment by pvoigtlaender** [comment]
Did you put the images in /data/KITTI_MOTS/train/images/ ?

**Comment by AliRashidnejad** [comment]
@99demaster it's a simple rename: 
I had the same issue too, tried to change KITTI folder name /train/images_2 to train/images/ and it could then read read images and feed the list to have len(l)>0 .

**Comment by LiXm1002** [comment]
Hi,"/data/KITTI_MOTS/train/" should be built by ourself?

**Comment by LiXm1002** [comment]
Hi ,"/data/KITTI_MOTS/train/" should be built by ourself? or it has been built code author，I didn‘t find it.

**Comment by 99demaster** [comment]
I have already solved it by correcting the directory path.

**Comment by EchoAmor** [comment]
Sorry to disturb you , I met the same problem like you now , can you tell me how you solved it? Thanks very much! @99demaster
