### ISSUE TITLE
Can other resolutions for the images be used for a custom dataset?

### ISSUE THREAD

**Issue by jong372** [VisualComputingInstitute/TrackR-CNN#91]
Can other resolutions for the images be used for a custom dataset? Or is 'TrackR-CNN' limited to the resolution of the Kitti_MOTS dataset (1242x375)?

**Comment by pvoigtlaender** [comment]
You can use other resolutions. Note that for KITTI MOTS we specified a fixed size in the config, but for MOTSChallenge this is different, so please take a look at the MOTSChallenge config files.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
