### ISSUE TITLE
Amount of instances within video restricted to 1000?

### ISSUE THREAD

**Issue by jong372** [VisualComputingInstitute/TrackR-CNN#92]
Is the annotation format limited to the fact that it only allows 1000 instances within 1 video? Because otherwise you get troubles with the class id and object instance id.
According to your txt format: 

> time frame 52
> object id 1005 (meaning class id is 1, i.e. car and instance id is 5)
> class id 1
> image height 375
> image width 1242
> rle WSV:2d;1O10000O10000O1O100O100O1O100O1000000000000000O100O...1O1N

Hence, can this be easily changed in your code to 10000 e.g. ? Or is it better to cut the videos into multiple pieces?
Thanks in advance!

**Comment by pvoigtlaender** [comment]
Hi,

yes, the file format restricts it to 1000 instances per video, but this is a lot, it's distinct instances in the whole video (the same id is used for the same object in different frames). I think it's unlikely to have a video with more than 1000 distinct objects.
If this is really needed, it should be relatively easy to change it to 10000.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
