### ISSUE TITLE
AssertionError: usage: main.py

### ISSUE THREAD

**Issue by kcabhishek** [VisualComputingInstitute/TrackR-CNN#94]
I tried to run 
**python main.py configs/conv3d_sep2 "{\"task\":\"forward_tracking\",\"dataset\":\"KITTI_segtrack_feed\",\"load_epoch_no\":5,\"batch_size\":5,\"export_detections\":true,\"do_tracking\":false,\"video_tags_to_load\":[\"0002\",\"0006\",\"0007\",\"0008\",\"0010\",\"0013\",\"0014\",\"0016\",\"0018\",\"0000\",\"0001\",\"0003\",\"0004\",\"0005\",\"0009\",\"0011\",\"0012\",\"0015\",\"0017\",\"0019\",\"0020\"]}"**

then it gave me this error.

![errcnn](https://user-images.githubusercontent.com/31674144/94971853-9fc18a00-04cd-11eb-8a8e-7208fe5af246.PNG)
 
Did anyone else had to deal with this error. Can anyone help me solve this? I will really appreciate it.

**Comment by ahnonay** [comment]
You have to be a bit careful when using the optional_config_string: You need to escape the " characters in there. Try copying one of the example usages from the readme

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
