### ISSUE TITLE
Hello,I want to know whether the segmentation module can segment binary images

### ISSUE THREAD

**Issue by XiaoBingCQY** [VisualComputingInstitute/TrackR-CNN#97]

**Comment by ahnonay** [comment]
I am not sure whether I understand your question correctly. The system is trained on real-world images, so inputing binary images will probably produce nonsense results.

**Comment by XiaoBingCQY** [comment]
I mean whether the system can segment the following pictures.I'm very sorry to trouble you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualComputingInstitute/TrackR-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 下午5:27
收件人:&nbsp;"VisualComputingInstitute/TrackR-CNN"<TrackR-CNN@noreply.github.com&gt;;
抄送:&nbsp;"591956503"<591956503@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualComputingInstitute/TrackR-CNN] Hello,I want to know whether the segmentation module can segment binary images (#97)





 
I am not sure whether I understand your question correctly. The system is trained on real-world images, so inputing binary images will probably produce nonsense results.

**Comment by ahnonay** [comment]
Hey, there is no pictures in your post.

**Comment by XiaoBingCQY** [comment]
Sorry，I have put the picture in the attachment .And can you give me your contact information,I have some questions want to consult to you.Thank you very much.






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "VisualComputingInstitute/TrackR-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月5日(星期四) 下午4:48
收件人:&nbsp;"VisualComputingInstitute/TrackR-CNN"<TrackR-CNN@noreply.github.com&gt;;
抄送:&nbsp;"591956503"<591956503@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualComputingInstitute/TrackR-CNN] Hello,I want to know whether the segmentation module can segment binary images (#97)





 
Hey, there is no pictures in your post.

**Comment by ahnonay** [comment]
Hey, again, I cannot see pictures in your post. Contact information can be found e.g. in our paper, although asking questions on github is also nice so that other people can benefit from the answers.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
