### ISSUE TITLE
ValueError: The provided tag was already used for this event type

### ISSUE THREAD

**Issue by Snehabahl123** [VisualComputingInstitute/TrackR-CNN#98]
![image](https://user-images.githubusercontent.com/18510037/97138737-ddd56500-177e-11eb-99eb-e4777398b0bc.png)

I am getting the above error multiple times .
I got it while training a new model from scratch.
I also got it while forwarding and tracking from the pre saved model
It works fine for the first video tag (0002), from the next video tag onwards I get the above error.
I also tried passing a single video tag(0006) and I still get the error.

**Comment by ahnonay** [comment]
Hey! I have not seen this error before. The Tensorflow profiler seems to be active, which should not happen. Also maybe you can disable the writing of that summary (just comment out line 201 in Trainer.py) , since that seems to be the cause of the issue

**Comment by Snehabahl123** [comment]
How to set the tensorflow profiler to be inactive?

Also increasing the threshold in the summary writing code(line 201) fixed that issue

**Comment by ahnonay** [comment]
I'm not too familiar with the profiler, you need to consult the documentation. Good to hear that the issue was fixed.
