### ISSUE TITLE
Over usage of RAM

### ISSUE THREAD

**Issue by Snehabahl123** [VisualComputingInstitute/TrackR-CNN#99]
I don't understand why does the RAM usage increase so much.. 
I am running the code on Colab Pro.
and within 1680 / 39544  the approximately 25GB RAM get's used up
![image](https://user-images.githubusercontent.com/18510037/97862899-23b89d00-1d2c-11eb-978b-fcc96d5d996e.png)

**Comment by ahnonay** [comment]
The code is not optimized to minimize RAM usage. The machines we trained on typically had 32GB RAM available.

**Comment by Snehabahl123** [comment]
okay
Any way around it? any suggestions on how we could improve it?

Thanks

**Comment by ahnonay** [comment]
Maybe decreasing the batch size can help, but I'm not sure

**Comment by Snehabahl123** [comment]
Thanks
